In [1]:
import pandas as pd

In [2]:
b=pd.read_csv("badminton_dataset.csv")
b

     Outlook Temperature Humidity    Wind Play_Badminton
0   Overcast        Cool     High    Weak            Yes
1      Sunny        Mild   Normal  Strong             No
2       Rain        Mild   Normal  Strong             No
3      Sunny        Cool     High    Weak            Yes
4      Sunny        Cool     High  Strong             No
5      Sunny        Mild     High  Strong             No
6       Rain        Cool   Normal  Strong             No
7       Rain        Cool     High  Strong             No
8      Sunny         Hot     High  Strong             No
9      Sunny         Hot   Normal  Strong             No
10  Overcast        Mild     High  Strong             No
11  Overcast         Hot     High  Strong             No
12     Sunny        Mild     High    Weak            Yes
13  Overcast         Hot   Normal  Strong             No
14     Sunny         Hot   Normal    Weak            Yes
15  Overcast        Cool   Normal  Strong             No
16      Rain        Cool     High    Weak             No
17     Sunny         Hot     High    Weak            Yes
18      Rain         Hot     High    Weak             No
19  Overcast        Cool     High  Strong             No
20      Rain         Hot   Normal  Strong             No
21      Rain        Mild   Normal    Weak             No
22     Sunny        Cool   Normal    Weak            Yes
23      Rain        Mild     High    Weak             No
24  Overcast        Cool   Normal    Weak            Yes
25      Rain        Cool   Normal    Weak             No
26      Rain         Hot     High  Strong             No
27  Overcast         Hot   Normal    Weak            Yes
28  Overcast        Mild     High    Weak            Yes
29      Rain        Mild     High  Strong             No
30  Overcast         Hot     High    Weak            Yes
31  Overcast        Mild   Normal    Weak            Yes
32     Sunny        Cool   Normal  Strong             No
33      Rain         Hot   Normal    Weak             No
34     Sunny        Mild   Normal    Weak            Yes
35  Overcast        Mild   Normal  Strong             No

In [3]:
b.isnull().sum()

Outlook           0
Temperature       0
Humidity          0
Wind              0
Play_Badminton    0
dtype: int64

In [4]:
b.describe()

         Outlook Temperature Humidity  Wind Play_Badminton
count         36          36       36    36             36
unique         3           3        2     2              2
top     Overcast        Cool     High  Weak             No
freq          12          12       18    18             24

In [5]:
b.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Outlook         36 non-null     object
 1   Temperature     36 non-null     object
 2   Humidity        36 non-null     object
 3   Wind            36 non-null     object
 4   Play_Badminton  36 non-null     object
dtypes: object(5)
memory usage: 1.5+ KB

In [6]:
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()
for i in b.columns:
    if b[i].dtype=="object":
        b[i]=l.fit_transform(b[i])

In [7]:
b

    Outlook  Temperature  Humidity  Wind  Play_Badminton
0         0            0         0     1               1
1         2            2         1     0               0
2         1            2         1     0               0
3         2            0         0     1               1
4         2            0         0     0               0
5         2            2         0     0               0
6         1            0         1     0               0
7         1            0         0     0               0
8         2            1         0     0               0
9         2            1         1     0               0
10        0            2         0     0               0
11        0            1         0     0               0
12        2            2         0     1               1
13        0            1         1     0               0
14        2            1         1     1               1
15        0            0         1     0               0
16        1            0         0     1               0
17        2            1         0     1               1
18        1            1         0     1               0
19        0            0         0     0               0
20        1            1         1     0               0
21        1            2         1     1               0
22        2            0         1     1               1
23        1            2         0     1               0
24        0            0         1     1               1
25        1            0         1     1               0
26        1            1         0     0               0
27        0            1         1     1               1
28        0            2         0     1               1
29        1            2         0     0               0
30        0            1         0     1               1
31        0            2         1     1               1
32        2            0         1     0               0
33        1            1         1     1               0
34        2            2         1     1               1
35        0            2         1     0               0

In [8]:
x=b[["Outlook","Temperature","Humidity","Wind"]]
y=b["Play_Badminton"]

In [9]:
from sklearn.model_selection import train_test_split