In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
a=pd.read_csv("/content/early_wakeup_health_dataset.csv")

In [4]:
a.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Person_ID,10000,10000,P09984,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age,10000.0,NaN,NaN,NaN,44.6667,17.5172,18.0,29.75,43.0,58.0,80.0
Gender,10000,3,Male,4851,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Height_cm,10000.0,NaN,NaN,NaN,168.64916,9.876706,145.0,161.4,168.2,175.5,205.5
Weight_kg,10000.0,NaN,NaN,NaN,73.10734,16.29195,33.6,61.3,72.0,83.5,166.6
...,...,...,...,...,...,...,...,...,...,...,...
Health_Score,10000.0,NaN,NaN,NaN,74.20136,12.266227,27.3,66.0,74.6,82.8,100.0
Fitness_Level,10000,4,Good,4429,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Healthy_Aging_Score,10000.0,NaN,NaN,NaN,74.81232,14.627688,12.4,65.3,75.7,85.7,100.0
Wellness_Category,10000,4,Good,4429,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Early_Waker,10000,2,No,5842,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df=pd.DataFrame(a)

In [6]:
df.head(10)

,Person_ID,Age,Gender,Height_cm,Weight_kg,BMI,Country,Occupation,Marital_Status,Wake_Up_Time,...,Obesity_Risk,Hypertension_Risk,Diabetes_Risk,Cardiovascular_Risk,Sleep_Disorder_Risk,Health_Score,Fitness_Level,Healthy_Aging_Score,Wellness_Category,Early_Waker
0,P00001,76,Female,158.8,62.1,24.63,Italy,Entrepreneur,Widowed,08:59,...,Low,High,Medium,Medium,Low,87.3,Excellent,81.8,Excellent,No
1,P00002,49,Female,160.9,68.5,26.45,USA,Freelancer,Single,06:35,...,Medium,Medium,Medium,Low,Medium,72.0,Good,75.2,Good,No
2,P00003,51,Female,151.9,54.8,23.77,Mexico,Nurse,Single,07:31,...,Low,Medium,Medium,Low,Low,75.2,Good,77.1,Good,No
3,P00004,48,Male,167.6,81.3,28.93,Australia,Laborer,Single,08:36,...,Medium,Medium,Low,Low,Medium,82.7,Excellent,87.1,Excellent,No
4,P00005,68,Female,171.9,75.4,25.51,USA,Software Engineer,Married,07:07,...,Medium,High,Medium,Medium,Low,62.7,Average,58.1,Average,No
5,P00006,79,Male,166.2,60.5,21.90,India,Accountant,Married,07:50,...,Low,High,Medium,High,Medium,60.6,Average,52.0,Average,No
6,P00007,74,Male,169.9,55.0,19.06,Canada,Software Engineer,Single,06:49,...,Low,High,Medium,Medium,Low,72.3,Good,66.7,Good,No
7,P00008,67,Female,160.8,82.5,31.91,Brazil,Retired,Single,06:11,...,High,High,Medium,Medium,Medium,46.7,Average,39.6,Average,Yes
8,P00009,22,Male,190.8,65.1,17.88,UK,Software Engineer,Single,06:54,...,Low,Low,Low,Low,Low,78.8,Good,90.2,Good,No
9,P00010,22,Male,177.9,90.7,28.67,Italy,Software Engineer,Single,07:06,...,Medium,High,Low,Low,Medium,70.0,Good,76.8,Good,No

In [7]:
df.tail(10)

,Person_ID,Age,Gender,Height_cm,Weight_kg,BMI,Country,Occupation,Marital_Status,Wake_Up_Time,...,Obesity_Risk,Hypertension_Risk,Diabetes_Risk,Cardiovascular_Risk,Sleep_Disorder_Risk,Health_Score,Fitness_Level,Healthy_Aging_Score,Wellness_Category,Early_Waker
9990,P09991,56,Female,159.6,48.5,19.03,USA,Nurse,Divorced,08:25,...,Low,High,Medium,Medium,Medium,84.7,Excellent,82.3,Excellent,No
9991,P09992,55,Female,145.4,44.3,20.96,Spain,Entrepreneur,Single,09:33,...,Low,High,Medium,Low,Low,82.8,Excellent,86.4,Excellent,No
9992,P09993,41,Female,156.8,69.6,28.31,Nigeria,Chef,Divorced,05:07,...,Medium,High,Medium,Low,Medium,82.2,Excellent,83.8,Excellent,Yes
9993,P09994,72,Male,167.8,81.4,28.92,India,Artist,Married,06:00,...,Medium,High,High,Medium,Low,77.5,Good,68.0,Good,Yes
9994,P09995,66,Male,184.1,92.4,27.26,Pakistan,Nurse,Divorced,07:27,...,Medium,High,Medium,Medium,Low,89.8,Excellent,87.3,Excellent,No
9995,P09996,66,Male,170.2,86.4,29.84,Nigeria,Teacher,Single,07:11,...,Medium,High,High,Medium,Low,67.8,Good,53.8,Good,No
9996,P09997,70,Male,182.3,86.9,26.14,Canada,Athlete,Single,09:33,...,Medium,High,Medium,Medium,Low,84.8,Excellent,78.5,Excellent,No
9997,P09998,29,Male,170.4,81.2,27.96,Italy,Lawyer,Married,07:58,...,Medium,Low,Medium,Low,Medium,54.2,Average,59.2,Average,No
9998,P09999,22,Male,186.5,78.3,22.52,India,Chef,Single,06:39,...,Low,Medium,Medium,Low,Medium,78.9,Good,84.2,Good,No
9999,P10000,58,Male,177.8,63.9,20.22,Brazil,Freelancer,Single,05:06,...,Low,Low,Low,Low,Low,88.7,Excellent,90.4,Excellent,Yes

In [8]:
df.shape

(10000, 64)

In [9]:
df.columns

Index(['Person_ID', 'Age', 'Gender', 'Height_cm', 'Weight_kg', 'BMI',
       'Country', 'Occupation', 'Marital_Status', 'Wake_Up_Time', 'Sleep_Time',
       'Sleep_Duration_Hours', 'Sleep_Quality_Score',
       'Number_of_Night_Awakenings', 'Weekend_Sleep_Difference_Hours',
       'Nap_Frequency_Per_Week', 'Screen_Time_Before_Bed_Hours',
       'Exercise_Frequency_Per_Week', 'Exercise_Duration_Minutes',
       'Exercise_Type', 'Daily_Steps', 'Morning_Workout', 'Workout_Intensity',
       'Gym_Member', 'Daily_Calorie_Intake', 'Water_Intake_Liters',
       'Fruit_Intake_Per_Day', 'Vegetable_Intake_Per_Day',
       'Protein_Intake_Grams', 'Sugary_Drinks_Per_Week',
       'Fast_Food_Meals_Per_Week', 'Breakfast_Regularity_Score',
       'Smoking_Status', 'Alcohol_Consumption', 'Stress_Level',
       'Working_Hours_Per_Day', 'Sitting_Hours_Per_Day', 'Outdoor_Time_Hours',
       'Social_Interaction_Score', 'Meditation_Practice', 'Resting_Heart_Rate',
       'Systolic_BP', 'Diastolic_BP', 'Cholesterol_Level', 'Blood_Sugar_Level',
       'Energy_Level_Score', 'Fatigue_Level_Score', 'Immune_Health_Score',
       'Mood_Score', 'Anxiety_Score', 'Depression_Risk_Score',
       'Productivity_Score', 'Focus_Concentration_Score',
       'Life_Satisfaction_Score', 'Obesity_Risk', 'Hypertension_Risk',
       'Diabetes_Risk', 'Cardiovascular_Risk', 'Sleep_Disorder_Risk',
       'Health_Score', 'Fitness_Level', 'Healthy_Aging_Score',
       'Wellness_Category', 'Early_Waker'],
      dtype='object')

In [10]:
df.dtypes

Person_ID               object
Age                      int64
Gender                  object
Height_cm              float64
Weight_kg              float64
                        ...
Health_Score           float64
Fitness_Level           object
Healthy_Aging_Score    float64
Wellness_Category       object
Early_Waker             object
Length: 64, dtype: object

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 64 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Person_ID                       10000 non-null  object
 1   Age                             10000 non-null  int64
 2   Gender                          10000 non-null  object
 3   Height_cm                       10000 non-null  float64
 4   Weight_kg                       10000 non-null  float64
 5   BMI                             10000 non-null  float64
 6   Country                         10000 non-null  object
 7   Occupation                      10000 non-null  object
 8   Marital_Status                  10000 non-null  object
 9   Wake_Up_Time                    10000 non-null  object
 10  Sleep_Time                      10000 non-null  object
 11  Sleep_Duration_Hours            10000 non-null  float64
 12  Sleep_Quality_Score             10000 non-null  float64
 13  Number_of_Night_Awakenings      10000 non-null  int64
 14  Weekend_Sleep_Difference_Hours  10000 non-null  float64
 15  Nap_Frequency_Per_Week          10000 non-null  int64
 16  Screen_Time_Before_Bed_Hours    10000 non-null  float64
 17  Exercise_Frequency_Per_Week     10000 non-null  int64
 18  Exercise_Duration_Minutes       10000 non-null  int64
 19  Exercise_Type                   9176 non-null   object
 20  Daily_Steps                     10000 non-null  int64
 21  Morning_Workout                 10000 non-null  object
 22  Workout_Intensity               9176 non-null   object
 23  Gym_Member                      10000 non-null  object
 24  Daily_Calorie_Intake            10000 non-null  int64
 25  Water_Intake_Liters             10000 non-null  float64
 26  Fruit_Intake_Per_Day            10000 non-null  int64
 27  Vegetable_Intake_Per_Day        10000 non-null  int64
 28  Protein_Intake_Grams            10000 non-null  float64
 29  Sugary_Drinks_Per_Week          10000 non-null  int64
 30  Fast_Food_Meals_Per_Week        10000 non-null  int64
 31  Breakfast_Regularity_Score      10000 non-null  float64
 32  Smoking_Status                  10000 non-null  object
 33  Alcohol_Consumption             6986 non-null   object
 34  Stress_Level                    10000 non-null  float64
 35  Working_Hours_Per_Day           10000 non-null  float64
 36  Sitting_Hours_Per_Day           10000 non-null  float64
 37  Outdoor_Time_Hours              10000 non-null  float64
 38  Social_Interaction_Score        10000 non-null  float64
 39  Meditation_Practice             10000 non-null  object
 40  Resting_Heart_Rate              10000 non-null  int64
 41  Systolic_BP                     10000 non-null  int64
 42  Diastolic_BP                    10000 non-null  int64
 43  Cholesterol_Level               10000 non-null  float64
 44  Blood_Sugar_Level               10000 non-null  float64
 45  Energy_Level_Score              10000 non-null  float64
 46  Fatigue_Level_Score             10000 non-null  float64
 47  Immune_Health_Score             10000 non-null  float64
 48  Mood_Score                      10000 non-null  float64
 49  Anxiety_Score                   10000 non-null  float64
 50  Depression_Risk_Score           10000 non-null  float64
 51  Productivity_Score              10000 non-null  float64
 52  Focus_Concentration_Score       10000 non-null  float64
 53  Life_Satisfaction_Score         10000 non-null  float64
 54  Obesity_Risk                    10000 non-null  object
 55  Hypertension_Risk               10000 non-null  object
 56  Diabetes_Risk                   10000 non-null  object
 57  Cardiovascular_Risk             10000 non-null  object
 58  Sleep_Disorder_Risk             10000 non-null  object
 59  Health_Score                    10000 non-null  float64
 60  Fitness_Level                   10000 non-null  object
 61  Healthy_Aging_Score             10000 non-null  float64
 62  Wellness_Category               10000 non-null  object
 63  Early_Waker                     10000 non-null  object
dtypes: float64(28), int64(14), object(22)
memory usage: 4.9+ MB

In [12]:
df[["Age","Early_Waker","Diabetes_Risk"]]

      Age Early_Waker Diabetes_Risk
0      76          No        Medium
1      49          No        Medium
2      51          No        Medium
3      48          No           Low
4      68          No        Medium
...   ...         ...           ...
9995   66          No          High
9996   70          No        Medium
9997   29          No        Medium
9998   22          No        Medium
9999   58         Yes           Low

[10000 rows x 3 columns]

In [13]:
df.iloc[1000]

Person_ID                 P01001
Age                           41
Gender                      Male
Height_cm                  162.9
Weight_kg                   65.8
                         ...
Health_Score                82.9
Fitness_Level          Excellent
Healthy_Aging_Score         78.5
Wellness_Category      Excellent
Early_Waker                  Yes
Name: 1000, Length: 64, dtype: object

In [14]:
df[a["Age"]>60]

,Person_ID,Age,Gender,Height_cm,Weight_kg,BMI,Country,Occupation,Marital_Status,Wake_Up_Time,...,Obesity_Risk,Hypertension_Risk,Diabetes_Risk,Cardiovascular_Risk,Sleep_Disorder_Risk,Health_Score,Fitness_Level,Healthy_Aging_Score,Wellness_Category,Early_Waker
0,P00001,76,Female,158.8,62.1,24.63,Italy,Entrepreneur,Widowed,08:59,...,Low,High,Medium,Medium,Low,87.3,Excellent,81.8,Excellent,No
4,P00005,68,Female,171.9,75.4,25.51,USA,Software Engineer,Married,07:07,...,Medium,High,Medium,Medium,Low,62.7,Average,58.1,Average,No
5,P00006,79,Male,166.2,60.5,21.90,India,Accountant,Married,07:50,...,Low,High,Medium,High,Medium,60.6,Average,52.0,Average,No
6,P00007,74,Male,169.9,55.0,19.06,Canada,Software Engineer,Single,06:49,...,Low,High,Medium,Medium,Low,72.3,Good,66.7,Good,No
7,P00008,67,Female,160.8,82.5,31.91,Brazil,Retired,Single,06:11,...,High,High,Medium,Medium,Medium,46.7,Average,39.6,Average,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,P09990,80,Male,180.2,88.2,27.18,Canada,Manager,Single,08:13,...,Medium,High,Low,High,Medium,47.6,Average,39.2,Average,No
9993,P09994,72,Male,167.8,81.4,28.92,India,Artist,Married,06:00,...,Medium,High,High,Medium,Low,77.5,Good,68.0,Good,Yes
9994,P09995,66,Male,184.1,92.4,27.26,Pakistan,Nurse,Divorced,07:27,...,Medium,High,Medium,Medium,Low,89.8,Excellent,87.3,Excellent,No
9995,P09996,66,Male,170.2,86.4,29.84,Nigeria,Teacher,Single,07:11,...,Medium,High,High,Medium,Low,67.8,Good,53.8,Good,No
9996,P09997,70,Male,182.3,86.9,26.14,Canada,Athlete,Single,09:33,...,Medium,High,Medium,Medium,Low,84.8,Excellent,78.5,Excellent,No

In [15]:
df[(df["Age"]>40)&(df["Gender"]=="Male")]

,Person_ID,Age,Gender,Height_cm,Weight_kg,BMI,Country,Occupation,Marital_Status,Wake_Up_Time,...,Obesity_Risk,Hypertension_Risk,Diabetes_Risk,Cardiovascular_Risk,Sleep_Disorder_Risk,Health_Score,Fitness_Level,Healthy_Aging_Score,Wellness_Category,Early_Waker
3,P00004,48,Male,167.6,81.3,28.93,Australia,Laborer,Single,08:36,...,Medium,Medium,Low,Low,Medium,82.7,Excellent,87.1,Excellent,No
5,P00006,79,Male,166.2,60.5,21.90,India,Accountant,Married,07:50,...,Low,High,Medium,High,Medium,60.6,Average,52.0,Average,No
6,P00007,74,Male,169.9,55.0,19.06,Canada,Software Engineer,Single,06:49,...,Low,High,Medium,Medium,Low,72.3,Good,66.7,Good,No
10,P00011,54,Male,174.0,65.2,21.54,UK,Manager,Widowed,05:49,...,Low,Medium,Medium,Medium,Medium,70.9,Good,69.9,Good,Yes
11,P00012,44,Male,183.6,75.2,22.30,France,Retired,Single,07:16,...,Low,High,Medium,Medium,Medium,78.7,Good,73.4,Good,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9993,P09994,72,Male,167.8,81.4,28.92,India,Artist,Married,06:00,...,Medium,High,High,Medium,Low,77.5,Good,68.0,Good,Yes
9994,P09995,66,Male,184.1,92.4,27.26,Pakistan,Nurse,Divorced,07:27,...,Medium,High,Medium,Medium,Low,89.8,Excellent,87.3,Excellent,No
9995,P09996,66,Male,170.2,86.4,29.84,Nigeria,Teacher,Single,07:11,...,Medium,High,High,Medium,Low,67.8,Good,53.8,Good,No
9996,P09997,70,Male,182.3,86.9,26.14,Canada,Athlete,Single,09:33,...,Medium,High,Medium,Medium,Low,84.8,Excellent,78.5,Excellent,No
9999,P10000,58,Male,177.8,63.9,20.22,Brazil,Freelancer,Single,05:06,...,Low,Low,Low,Low,Low,88.7,Excellent,90.4,Excellent,Yes

In [16]:
df.sort_values("Height_cm",ascending=False)

,Person_ID,Age,Gender,Height_cm,Weight_kg,BMI,Country,Occupation,Marital_Status,Wake_Up_Time,...,Obesity_Risk,Hypertension_Risk,Diabetes_Risk,Cardiovascular_Risk,Sleep_Disorder_Risk,Health_Score,Fitness_Level,Healthy_Aging_Score,Wellness_Category,Early_Waker
7638,P07639,35,Male,205.5,123.8,29.33,India,Nurse,Divorced,07:52,...,Medium,Medium,Low,Low,Medium,71.4,Good,80.6,Good,No
3408,P03409,72,Male,203.7,127.9,30.82,UK,Athlete,Single,05:14,...,High,High,Low,High,Medium,59.5,Average,52.3,Average,Yes
9695,P09696,57,Male,202.8,103.4,25.14,Brazil,Doctor,Widowed,08:58,...,Medium,Medium,Medium,Low,Low,87.6,Excellent,89.7,Excellent,No
5956,P05957,58,Male,202.3,67.7,16.54,Italy,Teacher,Married,07:21,...,Low,High,Medium,Medium,Low,82.1,Excellent,76.5,Excellent,No
6080,P06081,42,Male,200.6,76.6,19.03,India,Retired,Married,06:52,...,Low,Medium,Medium,Low,Medium,90.6,Excellent,95.9,Excellent,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
642,P00643,64,Non-binary,145.0,60.4,28.71,Spain,Freelancer,Divorced,06:39,...,Medium,High,Medium,Medium,Low,91.9,Excellent,87.1,Excellent,No
5102,P05103,49,Female,145.0,65.0,30.91,Nigeria,Software Engineer,Single,08:30,...,High,High,Medium,Medium,Medium,58.6,Average,54.8,Average,No
5142,P05143,44,Female,145.0,50.2,23.86,Pakistan,Lawyer,Divorced,04:00,...,Low,Medium,Low,Low,Medium,83.0,Excellent,91.2,Excellent,Yes
5337,P05338,25,Female,145.0,39.9,19.00,France,Student,Divorced,05:54,...,Low,High,Low,Low,Low,85.7,Excellent,95.8,Excellent,Yes
9909,P09910,56,Female,145.0,42.4,20.15,Brazil,Retired,Married,06:41,...,Low,Medium,Low,Low,Low,79.5,Good,85.1,Good,No

In [17]:
df.sort_values(["Age","Weight_kg"],ascending=False)

,Person_ID,Age,Gender,Height_cm,Weight_kg,BMI,Country,Occupation,Marital_Status,Wake_Up_Time,...,Obesity_Risk,Hypertension_Risk,Diabetes_Risk,Cardiovascular_Risk,Sleep_Disorder_Risk,Health_Score,Fitness_Level,Healthy_Aging_Score,Wellness_Category,Early_Waker
3821,P03822,80,Male,187.5,124.9,35.53,Mexico,Retired,Married,09:27,...,High,High,Medium,Medium,Low,72.3,Good,67.3,Good,No
3261,P03262,80,Male,193.2,124.7,33.41,Italy,Freelancer,Married,08:42,...,High,High,Low,High,Low,62.1,Average,52.4,Average,No
1405,P01406,80,Male,181.4,119.9,36.43,Canada,Software Engineer,Single,07:45,...,High,High,Medium,High,Medium,59.4,Average,46.9,Average,No
1436,P01437,80,Male,179.2,111.6,34.76,Pakistan,Doctor,Divorced,05:06,...,High,High,Medium,High,Low,78.6,Good,67.3,Good,Yes
7398,P07399,80,Male,180.6,110.0,33.73,India,Retired,Married,07:31,...,High,High,Medium,High,Medium,67.5,Good,58.8,Good,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5868,P05869,18,Male,156.6,45.8,18.69,Pakistan,Accountant,Married,08:08,...,Low,Medium,Low,Low,Low,85.1,Excellent,95.8,Excellent,No
7876,P07877,18,Male,166.7,44.5,16.00,India,Freelancer,Married,07:24,...,Low,Medium,Low,Low,Medium,76.2,Good,85.1,Good,No
5088,P05089,18,Female,165.7,43.9,16.00,USA,Entrepreneur,Single,08:54,...,Low,Low,Low,Low,Medium,59.2,Average,66.5,Average,No
3694,P03695,18,Female,152.3,41.7,17.99,Pakistan,Laborer,Single,07:50,...,Low,Low,Medium,Low,Low,88.0,Excellent,90.5,Excellent,No
4277,P04278,18,Female,155.3,38.6,16.00,Italy,Lawyer,Divorced,07:24,...,Low,Low,Low,Low,Low,86.6,Excellent,94.0,Excellent,No

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 64 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Person_ID                       10000 non-null  object
 1   Age                             10000 non-null  int64
 2   Gender                          10000 non-null  object
 3   Height_cm                       10000 non-null  float64
 4   Weight_kg                       10000 non-null  float64
 5   BMI                             10000 non-null  float64
 6   Country                         10000 non-null  object
 7   Occupation                      10000 non-null  object
 8   Marital_Status                  10000 non-null  object
 9   Wake_Up_Time                    10000 non-null  object
 10  Sleep_Time                      10000 non-null  object
 11  Sleep_Duration_Hours            10000 non-null  float64
 12  Sleep_Quality_Score             10000 non-null  float64
 13  Number_of_Night_Awakenings      10000 non-null  int64
 14  Weekend_Sleep_Difference_Hours  10000 non-null  float64
 15  Nap_Frequency_Per_Week          10000 non-null  int64
 16  Screen_Time_Before_Bed_Hours    10000 non-null  float64
 17  Exercise_Frequency_Per_Week     10000 non-null  int64
 18  Exercise_Duration_Minutes       10000 non-null  int64
 19  Exercise_Type                   9176 non-null   object
 20  Daily_Steps                     10000 non-null  int64
 21  Morning_Workout                 10000 non-null  object
 22  Workout_Intensity               9176 non-null   object
 23  Gym_Member                      10000 non-null  object
 24  Daily_Calorie_Intake            10000 non-null  int64
 25  Water_Intake_Liters             10000 non-null  float64
 26  Fruit_Intake_Per_Day            10000 non-null  int64
 27  Vegetable_Intake_Per_Day        10000 non-null  int64
 28  Protein_Intake_Grams            10000 non-null  float64
 29  Sugary_Drinks_Per_Week          10000 non-null  int64
 30  Fast_Food_Meals_Per_Week        10000 non-null  int64
 31  Breakfast_Regularity_Score      10000 non-null  float64
 32  Smoking_Status                  10000 non-null  object
 33  Alcohol_Consumption             6986 non-null   object
 34  Stress_Level                    10000 non-null  float64
 35  Working_Hours_Per_Day           10000 non-null  float64
 36  Sitting_Hours_Per_Day           10000 non-null  float64
 37  Outdoor_Time_Hours              10000 non-null  float64
 38  Social_Interaction_Score        10000 non-null  float64
 39  Meditation_Practice             10000 non-null  object
 40  Resting_Heart_Rate              10000 non-null  int64
 41  Systolic_BP                     10000 non-null  int64
 42  Diastolic_BP                    10000 non-null  int64
 43  Cholesterol_Level               10000 non-null  float64
 44  Blood_Sugar_Level               10000 non-null  float64
 45  Energy_Level_Score              10000 non-null  float64
 46  Fatigue_Level_Score             10000 non-null  float64
 47  Immune_Health_Score             10000 non-null  float64
 48  Mood_Score                      10000 non-null  float64
 49  Anxiety_Score                   10000 non-null  float64
 50  Depression_Risk_Score           10000 non-null  float64
 51  Productivity_Score              10000 non-null  float64
 52  Focus_Concentration_Score       10000 non-null  float64
 53  Life_Satisfaction_Score         10000 non-null  float64
 54  Obesity_Risk                    10000 non-null  object
 55  Hypertension_Risk               10000 non-null  object
 56  Diabetes_Risk                   10000 non-null  object
 57  Cardiovascular_Risk             10000 non-null  object
 58  Sleep_Disorder_Risk             10000 non-null  object
 59  Health_Score                    10000 non-null  float64
 60  Fitness_Level                   10000 non-null  object
 61  Healthy_Aging_Score             10000 non-null  float64
 62  Wellness_Category               10000 non-null  object
 63  Early_Waker                     10000 non-null  object
dtypes: float64(28), int64(14), object(22)
memory usage: 4.9+ MB

In [19]:
df.isnull().sum().sort_values(ascending=False)

Alcohol_Consumption    3014
Workout_Intensity       824
Exercise_Type           824
Person_ID                 0
Weight_kg                 0
                       ...
Health_Score              0
Fitness_Level             0
Healthy_Aging_Score       0
Wellness_Category         0
Early_Waker               0
Length: 64, dtype: int64

In [20]:
df.columns

Index(['Person_ID', 'Age', 'Gender', 'Height_cm', 'Weight_kg', 'BMI',
       'Country', 'Occupation', 'Marital_Status', 'Wake_Up_Time', 'Sleep_Time',
       'Sleep_Duration_Hours', 'Sleep_Quality_Score',
       'Number_of_Night_Awakenings', 'Weekend_Sleep_Difference_Hours',
       'Nap_Frequency_Per_Week', 'Screen_Time_Before_Bed_Hours',
       'Exercise_Frequency_Per_Week', 'Exercise_Duration_Minutes',
       'Exercise_Type', 'Daily_Steps', 'Morning_Workout', 'Workout_Intensity',
       'Gym_Member', 'Daily_Calorie_Intake', 'Water_Intake_Liters',
       'Fruit_Intake_Per_Day', 'Vegetable_Intake_Per_Day',
       'Protein_Intake_Grams', 'Sugary_Drinks_Per_Week',
       'Fast_Food_Meals_Per_Week', 'Breakfast_Regularity_Score',
       'Smoking_Status', 'Alcohol_Consumption', 'Stress_Level',
       'Working_Hours_Per_Day', 'Sitting_Hours_Per_Day', 'Outdoor_Time_Hours',
       'Social_Interaction_Score', 'Meditation_Practice', 'Resting_Heart_Rate',
       'Systolic_BP', 'Diastolic_BP', 'Cholesterol_Level', 'Blood_Sugar_Level',
       'Energy_Level_Score', 'Fatigue_Level_Score', 'Immune_Health_Score',
       'Mood_Score', 'Anxiety_Score', 'Depression_Risk_Score',
       'Productivity_Score', 'Focus_Concentration_Score',
       'Life_Satisfaction_Score', 'Obesity_Risk', 'Hypertension_Risk',
       'Diabetes_Risk', 'Cardiovascular_Risk', 'Sleep_Disorder_Risk',
       'Health_Score', 'Fitness_Level', 'Healthy_Aging_Score',
       'Wellness_Category', 'Early_Waker'],
      dtype='object')

In [27]:
f=df["Alcohol_Consumption"].dropna(inplace=True)
f

In [28]:
df.columns

Index(['Person_ID', 'Age', 'Gender', 'Height_cm', 'Weight_kg', 'BMI',
       'Country', 'Occupation', 'Marital_Status', 'Wake_Up_Time', 'Sleep_Time',
       'Sleep_Duration_Hours', 'Sleep_Quality_Score',
       'Number_of_Night_Awakenings', 'Weekend_Sleep_Difference_Hours',
       'Nap_Frequency_Per_Week', 'Screen_Time_Before_Bed_Hours',
       'Exercise_Frequency_Per_Week', 'Exercise_Duration_Minutes',
       'Exercise_Type', 'Daily_Steps', 'Morning_Workout', 'Workout_Intensity',
       'Gym_Member', 'Daily_Calorie_Intake', 'Water_Intake_Liters',
       'Fruit_Intake_Per_Day', 'Vegetable_Intake_Per_Day',
       'Protein_Intake_Grams', 'Sugary_Drinks_Per_Week',
       'Fast_Food_Meals_Per_Week', 'Breakfast_Regularity_Score',
       'Smoking_Status', 'Alcohol_Consumption', 'Stress_Level',
       'Working_Hours_Per_Day', 'Sitting_Hours_Per_Day', 'Outdoor_Time_Hours',
       'Social_Interaction_Score', 'Meditation_Practice', 'Resting_Heart_Rate',
       'Systolic_BP', 'Diastolic_BP', 'Cholesterol_Level', 'Blood_Sugar_Level',
       'Energy_Level_Score', 'Fatigue_Level_Score', 'Immune_Health_Score',
       'Mood_Score', 'Anxiety_Score', 'Depression_Risk_Score',
       'Productivity_Score', 'Focus_Concentration_Score',
       'Life_Satisfaction_Score', 'Obesity_Risk', 'Hypertension_Risk',
       'Diabetes_Risk', 'Cardiovascular_Risk', 'Sleep_Disorder_Risk',
       'Health_Score', 'Fitness_Level', 'Healthy_Aging_Score',
       'Wellness_Category', 'Early_Waker'],
      dtype='object')

In [37]:
df.rename(columns={"Early_Waker":"Early"},inplace=True)

In [38]:
df.columns

Index(['Person_ID', 'Age', 'Gender', 'Height_cm', 'Weight_kg', 'BMI',
       'Country', 'Occupation', 'Marital_Status', 'Wake_Up_Time', 'Sleep_Time',
       'Sleep_Duration_Hours', 'Sleep_Quality_Score',
       'Number_of_Night_Awakenings', 'Weekend_Sleep_Difference_Hours',
       'Nap_Frequency_Per_Week', 'Screen_Time_Before_Bed_Hours',
       'Exercise_Frequency_Per_Week', 'Exercise_Duration_Minutes',
       'Exercise_Type', 'Daily_Steps', 'Morning_Workout', 'Workout_Intensity',
       'Gym_Member', 'Daily_Calorie_Intake', 'Water_Intake_Liters',
       'Fruit_Intake_Per_Day', 'Vegetable_Intake_Per_Day',
       'Protein_Intake_Grams', 'Sugary_Drinks_Per_Week',
       'Fast_Food_Meals_Per_Week', 'Breakfast_Regularity_Score',
       'Smoking_Status', 'Alcohol_Consumption', 'Stress_Level',
       'Working_Hours_Per_Day', 'Sitting_Hours_Per_Day', 'Outdoor_Time_Hours',
       'Social_Interaction_Score', 'Meditation_Practice', 'Resting_Heart_Rate',
       'Systolic_BP', 'Diastolic_BP', 'Cholesterol_Level', 'Blood_Sugar_Level',
       'Energy_Level_Score', 'Fatigue_Level_Score', 'Immune_Health_Score',
       'Mood_Score', 'Anxiety_Score', 'Depression_Risk_Score',
       'Productivity_Score', 'Focus_Concentration_Score',
       'Life_Satisfaction_Score', 'Obesity_Risk', 'Hypertension_Risk',
       'Diabetes_Risk', 'Cardiovascular_Risk', 'Sleep_Disorder_Risk',
       'Health_Score', 'Fitness_Level', 'Healthy_Aging_Score',
       'Wellness_Category', 'Early', 'arly_Waker'],
      dtype='object')

In [39]:
df.drop("arly_Waker",axis=1)

,Person_ID,Age,Gender,Height_cm,Weight_kg,BMI,Country,Occupation,Marital_Status,Wake_Up_Time,...,Obesity_Risk,Hypertension_Risk,Diabetes_Risk,Cardiovascular_Risk,Sleep_Disorder_Risk,Health_Score,Fitness_Level,Healthy_Aging_Score,Wellness_Category,Early
0,P00001,76,Female,158.8,62.1,24.63,Italy,Entrepreneur,Widowed,08:59,...,Low,High,Medium,Medium,Low,87.3,Excellent,81.8,Excellent,No
1,P00002,49,Female,160.9,68.5,26.45,USA,Freelancer,Single,06:35,...,Medium,Medium,Medium,Low,Medium,72.0,Good,75.2,Good,No
2,P00003,51,Female,151.9,54.8,23.77,Mexico,Nurse,Single,07:31,...,Low,Medium,Medium,Low,Low,75.2,Good,77.1,Good,No
3,P00004,48,Male,167.6,81.3,28.93,Australia,Laborer,Single,08:36,...,Medium,Medium,Low,Low,Medium,82.7,Excellent,87.1,Excellent,No
4,P00005,68,Female,171.9,75.4,25.51,USA,Software Engineer,Married,07:07,...,Medium,High,Medium,Medium,Low,62.7,Average,58.1,Average,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,P09996,66,Male,170.2,86.4,29.84,Nigeria,Teacher,Single,07:11,...,Medium,High,High,Medium,Low,67.8,Good,53.8,Good,No
9996,P09997,70,Male,182.3,86.9,26.14,Canada,Athlete,Single,09:33,...,Medium,High,Medium,Medium,Low,84.8,Excellent,78.5,Excellent,No
9997,P09998,29,Male,170.4,81.2,27.96,Italy,Lawyer,Married,07:58,...,Medium,Low,Medium,Low,Medium,54.2,Average,59.2,Average,No
9998,P09999,22,Male,186.5,78.3,22.52,India,Chef,Single,06:39,...,Low,Medium,Medium,Low,Medium,78.9,Good,84.2,Good,No
9999,P10000,58,Male,177.8,63.9,20.22,Brazil,Freelancer,Single,05:06,...,Low,Low,Low,Low,Low,88.7,Excellent,90.4,Excellent,Yes

In [40]:
df["Sitting_Hours_Per_Day"].unique()

array([ 7.9,  4.8,  7.4,  7.1,  4. ,  4.6,  7.3,  6.9,  5.5,  5.7,  7. ,
        8.1,  5.2,  4.5,  6.4,  4.2,  6.3,  5.6,  5.1,  9.6,  2.6,  8.3,
        6.2,  6.5, 10.2,  9. ,  8.9,  6. ,  7.5,  8.5,  3.8,  9.3, 10.4,
        9.9, 10.1,  6.8,  8.2, 10.9,  9.7,  6.1, 10.6, 10.5,  7.7,  5.9,
        8.4,  5.4,  6.7,  8. ,  7.6,  7.2,  9.5,  7.8,  9.1, 10.7,  9.4,
        4.9,  9.2, 11.4, 12.8,  8.7,  6.6,  3.4,  9.8,  3.9,  4.3,  3.6,
        8.6, 10.3,  3.5, 11.1,  3.7, 11.2,  2. ,  4.4,  2.3,  5.3, 11.5,
        5. , 11. ,  8.8, 10.8,  5.8,  1.7, 11.8, 12. ,  3.1, 10. ,  3.2,
        4.7, 11.9, 12.2, 12.5, 11.7,  2.2, 12.6, 11.6, 12.4, 11.3,  3. ,
        2.7, 13. ,  4.1,  1.8,  1.6, 13.7,  2.9, 12.1,  2.1, 12.3,  3.3,
       13.4, 12.9, 13.5,  2.8,  1. , 14. ,  1.1, 13.1,  1.3,  1.9,  2.5,
       12.7, 13.3,  2.4, 13.2, 13.9,  1.5,  1.4, 13.6])

In [41]:
df["Sitting_Hours_Per_Day"].nunique()

129

In [42]:
df["Sitting_Hours_Per_Day"].value_counts()

Sitting_Hours_Per_Day
8.0     230
7.9     220
7.1     210
7.5     204
7.3     196
       ...
1.9       3
13.6      3
13.9      3
1.6       2
1.3       2
Name: count, Length: 129, dtype: int64

In [43]:
df["Sitting_Hours_Per_Day"].mean()

np.float64(7.59335)

In [44]:
df["Sitting_Hours_Per_Day"].median()

7.6

In [45]:
df["Sitting_Hours_Per_Day"].mode()

0    8.0
Name: Sitting_Hours_Per_Day, dtype: float64

In [46]:
df["Sitting_Hours_Per_Day"].max()

14.0

In [47]:
df["Sitting_Hours_Per_Day"].min()

1.0

In [59]:
df.groupby("Weight_kg")["Outdoor_Time_Hours"].agg(["mean","max","median"])

           mean   max  median
Weight_kg
33.6       2.48  2.48    2.48
35.0       5.46  5.46    5.46
35.1       1.73  1.73    1.73
35.7       1.19  1.19    1.19
36.0       7.94  7.94    7.94
...         ...   ...     ...
136.8      1.41  1.41    1.41
139.0      3.65  3.65    3.65
143.9      6.03  6.03    6.03
152.0      1.00  1.00    1.00
166.6      3.01  3.01    3.01

[847 rows x 3 columns]

In [63]:
df.duplicated().unique()

array([False])

In [64]:
df.drop_duplicates()

,Person_ID,Age,Gender,Height_cm,Weight_kg,BMI,Country,Occupation,Marital_Status,Wake_Up_Time,...,Hypertension_Risk,Diabetes_Risk,Cardiovascular_Risk,Sleep_Disorder_Risk,Health_Score,Fitness_Level,Healthy_Aging_Score,Wellness_Category,Early,arly_Waker
0,P00001,76,Female,158.8,62.1,24.63,Italy,Entrepreneur,Widowed,08:59,...,High,Medium,Medium,Low,87.3,Excellent,81.8,Excellent,No,No
1,P00002,49,Female,160.9,68.5,26.45,USA,Freelancer,Single,06:35,...,Medium,Medium,Low,Medium,72.0,Good,75.2,Good,No,No
2,P00003,51,Female,151.9,54.8,23.77,Mexico,Nurse,Single,07:31,...,Medium,Medium,Low,Low,75.2,Good,77.1,Good,No,No
3,P00004,48,Male,167.6,81.3,28.93,Australia,Laborer,Single,08:36,...,Medium,Low,Low,Medium,82.7,Excellent,87.1,Excellent,No,No
4,P00005,68,Female,171.9,75.4,25.51,USA,Software Engineer,Married,07:07,...,High,Medium,Medium,Low,62.7,Average,58.1,Average,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,P09996,66,Male,170.2,86.4,29.84,Nigeria,Teacher,Single,07:11,...,High,High,Medium,Low,67.8,Good,53.8,Good,No,No
9996,P09997,70,Male,182.3,86.9,26.14,Canada,Athlete,Single,09:33,...,High,Medium,Medium,Low,84.8,Excellent,78.5,Excellent,No,No
9997,P09998,29,Male,170.4,81.2,27.96,Italy,Lawyer,Married,07:58,...,Low,Medium,Low,Medium,54.2,Average,59.2,Average,No,No
9998,P09999,22,Male,186.5,78.3,22.52,India,Chef,Single,06:39,...,Medium,Medium,Low,Medium,78.9,Good,84.2,Good,No,No
9999,P10000,58,Male,177.8,63.9,20.22,Brazil,Freelancer,Single,05:06,...,Low,Low,Low,Low,88.7,Excellent,90.4,Excellent,Yes,Yes

In [70]:
df["Height_cm"]=df["Height_cm"].astype(int)
df

,Person_ID,Age,Gender,Height_cm,Weight_kg,BMI,Country,Occupation,Marital_Status,Wake_Up_Time,...,Hypertension_Risk,Diabetes_Risk,Cardiovascular_Risk,Sleep_Disorder_Risk,Health_Score,Fitness_Level,Healthy_Aging_Score,Wellness_Category,Early,arly_Waker
0,P00001,76,Female,158,62.1,24.63,Italy,Entrepreneur,Widowed,08:59,...,High,Medium,Medium,Low,87.3,Excellent,81.8,Excellent,No,No
1,P00002,49,Female,160,68.5,26.45,USA,Freelancer,Single,06:35,...,Medium,Medium,Low,Medium,72.0,Good,75.2,Good,No,No
2,P00003,51,Female,151,54.8,23.77,Mexico,Nurse,Single,07:31,...,Medium,Medium,Low,Low,75.2,Good,77.1,Good,No,No
3,P00004,48,Male,167,81.3,28.93,Australia,Laborer,Single,08:36,...,Medium,Low,Low,Medium,82.7,Excellent,87.1,Excellent,No,No
4,P00005,68,Female,171,75.4,25.51,USA,Software Engineer,Married,07:07,...,High,Medium,Medium,Low,62.7,Average,58.1,Average,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,P09996,66,Male,170,86.4,29.84,Nigeria,Teacher,Single,07:11,...,High,High,Medium,Low,67.8,Good,53.8,Good,No,No
9996,P09997,70,Male,182,86.9,26.14,Canada,Athlete,Single,09:33,...,High,Medium,Medium,Low,84.8,Excellent,78.5,Excellent,No,No
9997,P09998,29,Male,170,81.2,27.96,Italy,Lawyer,Married,07:58,...,Low,Medium,Low,Medium,54.2,Average,59.2,Average,No,No
9998,P09999,22,Male,186,78.3,22.52,India,Chef,Single,06:39,...,Medium,Medium,Low,Medium,78.9,Good,84.2,Good,No,No
9999,P10000,58,Male,177,63.9,20.22,Brazil,Freelancer,Single,05:06,...,Low,Low,Low,Low,88.7,Excellent,90.4,Excellent,Yes,Yes

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 65 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Person_ID                       10000 non-null  object
 1   Age                             10000 non-null  int64
 2   Gender                          10000 non-null  object
 3   Height_cm                       10000 non-null  int64
 4   Weight_kg                       10000 non-null  float64
 5   BMI                             10000 non-null  float64
 6   Country                         10000 non-null  object
 7   Occupation                      10000 non-null  object
 8   Marital_Status                  10000 non-null  object
 9   Wake_Up_Time                    10000 non-null  object
 10  Sleep_Time                      10000 non-null  object
 11  Sleep_Duration_Hours            10000 non-null  float64
 12  Sleep_Quality_Score             10000 non-null  float64
 13  Number_of_Night_Awakenings      10000 non-null  int64
 14  Weekend_Sleep_Difference_Hours  10000 non-null  float64
 15  Nap_Frequency_Per_Week          10000 non-null  int64
 16  Screen_Time_Before_Bed_Hours    10000 non-null  float64
 17  Exercise_Frequency_Per_Week     10000 non-null  int64
 18  Exercise_Duration_Minutes       10000 non-null  int64
 19  Exercise_Type                   9176 non-null   object
 20  Daily_Steps                     10000 non-null  int64
 21  Morning_Workout                 10000 non-null  object
 22  Workout_Intensity               9176 non-null   object
 23  Gym_Member                      10000 non-null  object
 24  Daily_Calorie_Intake            10000 non-null  int64
 25  Water_Intake_Liters             10000 non-null  float64
 26  Fruit_Intake_Per_Day            10000 non-null  int64
 27  Vegetable_Intake_Per_Day        10000 non-null  int64
 28  Protein_Intake_Grams            10000 non-null  float64
 29  Sugary_Drinks_Per_Week          10000 non-null  int64
 30  Fast_Food_Meals_Per_Week        10000 non-null  int64
 31  Breakfast_Regularity_Score      10000 non-null  float64
 32  Smoking_Status                  10000 non-null  object
 33  Alcohol_Consumption             6986 non-null   object
 34  Stress_Level                    10000 non-null  float64
 35  Working_Hours_Per_Day           10000 non-null  float64
 36  Sitting_Hours_Per_Day           10000 non-null  float64
 37  Outdoor_Time_Hours              10000 non-null  float64
 38  Social_Interaction_Score        10000 non-null  float64
 39  Meditation_Practice             10000 non-null  object
 40  Resting_Heart_Rate              10000 non-null  int64
 41  Systolic_BP                     10000 non-null  int64
 42  Diastolic_BP                    10000 non-null  int64
 43  Cholesterol_Level               10000 non-null  float64
 44  Blood_Sugar_Level               10000 non-null  float64
 45  Energy_Level_Score              10000 non-null  float64
 46  Fatigue_Level_Score             10000 non-null  float64
 47  Immune_Health_Score             10000 non-null  float64
 48  Mood_Score                      10000 non-null  float64
 49  Anxiety_Score                   10000 non-null  float64
 50  Depression_Risk_Score           10000 non-null  float64
 51  Productivity_Score              10000 non-null  float64
 52  Focus_Concentration_Score       10000 non-null  float64
 53  Life_Satisfaction_Score         10000 non-null  float64
 54  Obesity_Risk                    10000 non-null  object
 55  Hypertension_Risk               10000 non-null  object
 56  Diabetes_Risk                   10000 non-null  object
 57  Cardiovascular_Risk             10000 non-null  object
 58  Sleep_Disorder_Risk             10000 non-null  object
 59  Health_Score                    10000 non-null  float64
 60  Fitness_Level                   10000 non-null  object
 61  Healthy_Aging_Score             10000 non-null  float64
 62  Wellness_Category               10000 non-null  object
 63  Early                           10000 non-null  object
 64  arly_Waker                      10000 non-null  object
dtypes: float64(27), int64(15), object(23)
memory usage: 5.0+ MB

In [72]:
df.sample(10)

,Person_ID,Age,Gender,Height_cm,Weight_kg,BMI,Country,Occupation,Marital_Status,Wake_Up_Time,...,Hypertension_Risk,Diabetes_Risk,Cardiovascular_Risk,Sleep_Disorder_Risk,Health_Score,Fitness_Level,Healthy_Aging_Score,Wellness_Category,Early,arly_Waker
4343,P04344,75,Male,166,69.4,25.16,Japan,Software Engineer,Married,06:54,...,High,Low,Medium,Medium,66.6,Good,66.9,Good,No,No
777,P00778,28,Male,188,81.1,22.84,India,Nurse,Married,07:35,...,High,Low,Medium,Low,74.9,Good,75.3,Good,No,No
6142,P06143,21,Male,180,94.9,29.10,Canada,Nurse,Single,08:43,...,Low,Medium,Low,Low,85.8,Excellent,87.4,Excellent,No,No
5439,P05440,23,Male,167,65.5,23.49,USA,Artist,Married,06:44,...,Low,Medium,Low,Low,81.5,Excellent,81.7,Excellent,No,No
4392,P04393,63,Female,169,72.9,25.36,Nigeria,Retired,Divorced,04:31,...,Medium,Medium,Medium,Medium,65.8,Good,60.3,Good,Yes,Yes
4533,P04534,23,Male,156,60.8,24.68,France,Manager,Married,04:59,...,Medium,Medium,Low,Low,81.6,Excellent,85.6,Excellent,Yes,Yes
2083,P02084,62,Non-binary,164,80.0,29.45,Pakistan,Teacher,Single,07:20,...,Medium,Low,Low,Medium,69.7,Good,70.5,Good,No,No
6954,P06955,50,Male,160,68.3,26.54,USA,Lawyer,Widowed,05:48,...,High,Low,Low,Medium,83.0,Excellent,88.2,Excellent,Yes,Yes
2349,P02350,71,Male,171,68.4,23.16,France,Student,Married,11:00,...,High,Medium,Medium,Low,82.7,Excellent,77.4,Excellent,No,No
5221,P05222,50,Female,158,71.0,28.20,Mexico,Laborer,Married,04:08,...,Low,Medium,Low,Low,72.0,Good,71.3,Good,Yes,Yes

In [78]:
df.select_dtypes(include="object")

,Person_ID,Gender,Country,Occupation,Marital_Status,Wake_Up_Time,Sleep_Time,Exercise_Type,Morning_Workout,Workout_Intensity,...,Meditation_Practice,Obesity_Risk,Hypertension_Risk,Diabetes_Risk,Cardiovascular_Risk,Sleep_Disorder_Risk,Fitness_Level,Wellness_Category,Early,arly_Waker
0,P00001,Female,Italy,Entrepreneur,Widowed,08:59,01:29,Weight Training,No,Low,...,Yes,Low,High,Medium,Medium,Low,Excellent,Excellent,No,No
1,P00002,Female,USA,Freelancer,Single,06:35,02:25,Walking,Yes,Moderate,...,No,Medium,Medium,Medium,Low,Medium,Good,Good,No,No
2,P00003,Female,Mexico,Nurse,Single,07:31,02:24,NaN,No,NaN,...,No,Low,Medium,Medium,Low,Low,Good,Good,No,No
3,P00004,Male,Australia,Laborer,Single,08:36,01:19,Running,Yes,Moderate,...,No,Medium,Medium,Low,Low,Medium,Excellent,Excellent,No,No
4,P00005,Female,USA,Software Engineer,Married,07:07,01:20,NaN,No,NaN,...,No,Medium,High,Medium,Medium,Low,Average,Average,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,P09996,Male,Nigeria,Teacher,Single,07:11,00:03,Running,No,High,...,No,Medium,High,High,Medium,Low,Good,Good,No,No
9996,P09997,Male,Canada,Athlete,Single,09:33,01:29,HIIT,Yes,High,...,No,Medium,High,Medium,Medium,Low,Excellent,Excellent,No,No
9997,P09998,Male,Italy,Lawyer,Married,07:58,23:59,Running,No,Low,...,No,Medium,Low,Medium,Low,Medium,Average,Average,No,No
9998,P09999,Male,India,Chef,Single,06:39,01:45,Yoga,No,Moderate,...,No,Low,Medium,Medium,Low,Medium,Good,Good,No,No
9999,P10000,Male,Brazil,Freelancer,Single,05:06,21:50,Swimming,Yes,High,...,Yes,Low,Low,Low,Low,Low,Excellent,Excellent,Yes,Yes

In [77]:
df.index

RangeIndex(start=0, stop=10000, step=1)