In [1]:
import pandas as pd
df=pd.read_csv("PhishingData.csv")

In [2]:
df

,index,having_IPhaving_IP_Address,URLURL_Length,Shortining_Service,having_At_Symbol,double_slash_redirecting,Prefix_Suffix,having_Sub_Domain,SSLfinal_State,Domain_registeration_length,...,popUpWidnow,Iframe,age_of_domain,DNSRecord,web_traffic,Page_Rank,Google_Index,Links_pointing_to_page,Statistical_report,Result
0,1,-1,1,1,1,-1,-1,-1,-1,-1,...,1,1,-1,-1,-1,-1,1,1,-1,-1
1,2,1,1,1,1,1,-1,0,1,-1,...,1,1,-1,-1,0,-1,1,1,1,-1
2,3,1,0,1,1,1,-1,-1,-1,-1,...,1,1,1,-1,1,-1,1,0,-1,-1
3,4,1,0,1,1,1,-1,-1,-1,1,...,1,1,-1,-1,1,-1,1,-1,1,-1
4,5,1,0,-1,1,1,-1,1,1,-1,...,-1,1,-1,-1,0,-1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11050,11051,1,-1,1,-1,1,1,1,1,-1,...,-1,-1,1,1,-1,-1,1,1,1,1
11051,11052,-1,1,1,-1,-1,-1,1,-1,-1,...,-1,1,1,1,1,1,1,-1,1,-1
11052,11053,1,-1,1,1,1,-1,1,-1,-1,...,1,1,1,1,1,-1,1,0,1,-1
11053,11054,-1,-1,1,1,1,-1,-1,-1,1,...,-1,1,1,1,1,-1,1,1,1,-1
11054,11055,-1,-1,1,1,1,-1,-1,-1,1,...,1,1,-1,1,-1,-1,-1,1,-1,-1

In [3]:
df.columns[df.isna().any()]

Index([], dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11055 entries, 0 to 11054
Data columns (total 32 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   index                         11055 non-null  int64
 1   having_IPhaving_IP_Address    11055 non-null  int64
 2   URLURL_Length                 11055 non-null  int64
 3   Shortining_Service            11055 non-null  int64
 4   having_At_Symbol              11055 non-null  int64
 5   double_slash_redirecting      11055 non-null  int64
 6   Prefix_Suffix                 11055 non-null  int64
 7   having_Sub_Domain             11055 non-null  int64
 8   SSLfinal_State                11055 non-null  int64
 9   Domain_registeration_length   11055 non-null  int64
 10  Favicon                       11055 non-null  int64
 11  port                          11055 non-null  int64
 12  HTTPS_token                   11055 non-null  int64
 13  Request_URL                   11055 non-null  int64
 14  URL_of_Anchor                 11055 non-null  int64
 15  Links_in_tags                 11055 non-null  int64
 16  SFH                           11055 non-null  int64
 17  Submitting_to_email           11055 non-null  int64
 18  Abnormal_URL                  11055 non-null  int64
 19  Redirect                      11055 non-null  int64
 20  on_mouseover                  11055 non-null  int64
 21  RightClick                    11055 non-null  int64
 22  popUpWidnow                   11055 non-null  int64
 23  Iframe                        11055 non-null  int64
 24  age_of_domain                 11055 non-null  int64
 25  DNSRecord                     11055 non-null  int64
 26  web_traffic                   11055 non-null  int64
 27  Page_Rank                     11055 non-null  int64
 28  Google_Index                  11055 non-null  int64
 29  Links_pointing_to_page        11055 non-null  int64
 30  Statistical_report            11055 non-null  int64
 31  Result                        11055 non-null  int64
dtypes: int64(32)
memory usage: 2.7 MB

In [5]:
df.describe()

,index,having_IPhaving_IP_Address,URLURL_Length,Shortining_Service,having_At_Symbol,double_slash_redirecting,Prefix_Suffix,having_Sub_Domain,SSLfinal_State,Domain_registeration_length,...,popUpWidnow,Iframe,age_of_domain,DNSRecord,web_traffic,Page_Rank,Google_Index,Links_pointing_to_page,Statistical_report,Result
count,11055.000000,11055.000000,11055.000000,11055.000000,11055.000000,11055.000000,11055.000000,11055.000000,11055.000000,11055.000000,...,11055.000000,11055.000000,11055.000000,11055.000000,11055.000000,11055.000000,11055.000000,11055.000000,11055.000000,11055.000000
mean,5528.000000,0.313795,-0.633198,0.738761,0.700588,0.741474,-0.734962,0.063953,0.250927,-0.336771,...,0.613388,0.816915,0.061239,0.377114,0.287291,-0.483673,0.721574,0.344007,0.719584,0.113885
std,3191.447947,0.949534,0.766095,0.673998,0.713598,0.671011,0.678139,0.817518,0.911892,0.941629,...,0.789818,0.576784,0.998168,0.926209,0.827733,0.875289,0.692369,0.569944,0.694437,0.993539
min,1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
25%,2764.500000,-1.000000,-1.000000,1.000000,1.000000,1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,1.000000,1.000000,-1.000000,-1.000000,0.000000,-1.000000,1.000000,0.000000,1.000000,-1.000000
50%,5528.000000,1.000000,-1.000000,1.000000,1.000000,1.000000,-1.000000,0.000000,1.000000,-1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,-1.000000,1.000000,0.000000,1.000000,1.000000
75%,8291.500000,1.000000,-1.000000,1.000000,1.000000,1.000000,-1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,11055.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [6]:
#x=df.drop(columns=['index ','Result'])
#y=df["columns"]
#X = df.drop(columns=['Result', 'index'])
#print(df.columns)

In [7]:
df.columns = df.columns.str.strip()

In [8]:
df.columns

Index(['index', 'having_IPhaving_IP_Address', 'URLURL_Length',
       'Shortining_Service', 'having_At_Symbol', 'double_slash_redirecting',
       'Prefix_Suffix', 'having_Sub_Domain', 'SSLfinal_State',
       'Domain_registeration_length', 'Favicon', 'port', 'HTTPS_token',
       'Request_URL', 'URL_of_Anchor', 'Links_in_tags', 'SFH',
       'Submitting_to_email', 'Abnormal_URL', 'Redirect', 'on_mouseover',
       'RightClick', 'popUpWidnow', 'Iframe', 'age_of_domain', 'DNSRecord',
       'web_traffic', 'Page_Rank', 'Google_Index', 'Links_pointing_to_page',
       'Statistical_report', 'Result'],
      dtype='object')

In [9]:
x=df.drop(columns=['index','Result'])
x
y=df["Result"]
y

0       -1
1       -1
2       -1
3       -1
4        1
        ..
11050    1
11051   -1
11052   -1
11053   -1
11054   -1
Name: Result, Length: 11055, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [11]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.fit(x_train,y_train)

RandomForestClassifier()

In [12]:
y_pred=model.predict(x_test)
y_pred

array([-1, -1, -1, ..., -1,  1, -1])

In [13]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.9665309814563546

In [14]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[ 909   47]
 [  27 1228]]

In [15]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

          -1       0.97      0.95      0.96       956
           1       0.96      0.98      0.97      1255

    accuracy                           0.97      2211
   macro avg       0.97      0.96      0.97      2211
weighted avg       0.97      0.97      0.97      2211

In [16]:
#random forest

In [17]:
#from sklearn.ensemble import RandomForestclassifier
#from sklearn.ensemble import RandomForestClassifier
#model=randomForestClassifier()
#model.fit(x_train,y_train)

from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(x_train, y_train)

RandomForestClassifier()

In [18]:
y_pred=model.predict(x_test)
y_pred

array([-1, -1, -1, ..., -1,  1, -1])

In [19]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print("Accuracy of model training :",accuracy_score(y_test,y_pred))
print("confusion matrix :\n",confusion_matrix(y_test,y_pred))
print("classification_report:\n",classification_report(y_test,y_pred))

Accuracy of model training : 0.9674355495251018
confusion matrix :
 [[ 910   46]
 [  26 1229]]
classification_report:
               precision    recall  f1-score   support

          -1       0.97      0.95      0.96       956
           1       0.96      0.98      0.97      1255

    accuracy                           0.97      2211
   macro avg       0.97      0.97      0.97      2211
weighted avg       0.97      0.97      0.97      2211

In [27]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix


models = {
    "Logistic": LogisticRegression(max_iter=1000),
    "KNN": KNeighborsClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier()
}
for name,model in models.items():
    model.fit(x_train,y_train)
    y_pred=model.predict(x_test)
    print(name," -- Accuracy_score : ",accuracy_score(y_test,y_pred))
    print(name ,"confusion matrix :\n",confusion_matrix(y_test,y_pred))
    print(name,"classification_report:\n",classification_report(y_test,y_pred))
    print ("--------------------------------------")
    print ("--------------------------------------")

Logistic  -- Accuracy_score :  0.924468566259611
Logistic confusion matrix :
 [[ 865   91]
 [  76 1179]]
Logistic classification_report:
               precision    recall  f1-score   support

          -1       0.92      0.90      0.91       956
           1       0.93      0.94      0.93      1255

    accuracy                           0.92      2211
   macro avg       0.92      0.92      0.92      2211
weighted avg       0.92      0.92      0.92      2211

--------------------------------------
--------------------------------------
KNN  -- Accuracy_score :  0.9366802351876978
KNN confusion matrix :
 [[ 880   76]
 [  64 1191]]
KNN classification_report:
               precision    recall  f1-score   support

          -1       0.93      0.92      0.93       956
           1       0.94      0.95      0.94      1255

    accuracy                           0.94      2211
   macro avg       0.94      0.93      0.94      2211
weighted avg       0.94      0.94      0.94      2211

--------------------------------------
--------------------------------------
Decision Tree  -- Accuracy_score :  0.95838986883763
Decision Tree confusion matrix :
 [[ 907   49]
 [  43 1212]]
Decision Tree classification_report:
               precision    recall  f1-score   support

          -1       0.95      0.95      0.95       956
           1       0.96      0.97      0.96      1255

    accuracy                           0.96      2211
   macro avg       0.96      0.96      0.96      2211
weighted avg       0.96      0.96      0.96      2211

--------------------------------------
--------------------------------------
Random Forest  -- Accuracy_score :  0.9642695612844867
Random Forest confusion matrix :
 [[ 906   50]
 [  29 1226]]
Random Forest classification_report:
               precision    recall  f1-score   support

          -1       0.97      0.95      0.96       956
           1       0.96      0.98      0.97      1255

    accuracy                           0.96      2211
   macro avg       0.96      0.96      0.96      2211
weighted avg       0.96      0.96      0.96      2211

--------------------------------------
--------------------------------------

In [32]:
print(df["Result"])

0       -1
1       -1
2       -1
3       -1
4        1
        ..
11050    1
11051   -1
11052   -1
11053   -1
11054   -1
Name: Result, Length: 11055, dtype: int64

In [33]:
df["Result"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 11055 entries, 0 to 11054
Series name: Result
Non-Null Count  Dtype
--------------  -----
11055 non-null  int64
dtypes: int64(1)
memory usage: 86.5 KB

In [34]:
for i in df["Result"]:
    print(i)

-1
-1
-1
-1
1
1
-1
-1
1
-1
1
-1
-1
-1
1
-1
-1
-1
1
1
1
1
1
1
1
1
-1
1
1
1
1
1
1
1
-1
-1
-1
-1
1
1
1
1
-1
-1
-1
1
1
-1
-1
1
-1
1
1
-1
-1
-1
1
1
-1
-1
-1
-1
1
-1
1
1
-1
-1
1
-1
1
1
-1
1
-1
-1
1
1
-1
1
-1
1
1
1
1
-1
-1
1
1
-1
-1
1
1
-1
1
-1
-1
-1
-1
1
-1
-1
1
-1
1
-1
-1
-1
1
-1
1
-1
-1
1
-1
1
-1
-1
1
1
1
1
1
1
-1
1
1
1
1
-1
-1
1
-1
1
-1
1
-1
1
-1
-1
-1
-1
-1
-1
-1
-1
-1
1
1
1
1
1
1
1
-1
1
-1
-1
1
1
1
1
-1
1
-1
1
1
1
-1
1
-1
1
1
1
-1
1
-1
-1
1
1
1
1
1
-1
1
-1
1
-1
-1
1
1
-1
1
-1
-1
1
1
-1
-1
1
-1
1
1
1
-1
-1
1
1
1
-1
1
1
1
1
1
-1
1
1
-1
1
-1
1
1
-1
-1
-1
-1
1
1
-1
-1
1
1
1
1
1
1
1
1
-1
1
-1
-1
1
-1
-1
-1
-1
-1
-1
-1
-1
1
1
-1
1
-1
-1
1
1
1
1
1
1
-1
1
-1
1
1
1
-1
1
1
1
1
1
1
1
-1
1
1
-1
1
1
-1
-1
-1
1
1
-1
1
1
1
-1
1
1
1
-1
1
-1
1
-1
1
-1
1
1
1
1
1
1
1
-1
-1
1
1
-1
-1
1
1
-1
1
1
1
1
1
1
-1
-1
-1
1
1
1
1
1
-1
-1
1
-1
-1
1
1
1
1
1
1
1
-1
1
1
1
-1
1
-1
1
1
-1
1
1
1
1
-1
-1
1
-1
1
1
1
1
-1
-1
1
1
-1
1
-1
1
1
-1
1
1
1
1
-1
-1
-1
1
-1
1
1
-1
-1
1
1
-1
1
1
1
1
1
1
1
-1
1
1
1
1
1
1
1
1
1
1
1
1
-1
-1
-1
-1
-1
-1
-1
-1
1
1
1
-1
-1
1
1
1
1
1
1
1
-1
1
-1
1
1
1
1
-1
-1
1
-1
1
-1
1
-1
-1
1
-1
-1
-1
-1
1
1
1
-1
-1
-1
-1
1
1
1
1
-1
-1
1
1
-1
-1
1
1
-1
-1
-1
-1
-1
-1
1
-1
-1
-1
1
-1
1
-1
1
1
1
1
-1
-1
1
-1
1
1
-1
1
1
1
1
-1
1
1
1
1
1
1
1
1
-1
1
-1
-1
1
1
1
-1
-1
1
-1
1
1
1
-1
1
1
1
-1
-1
-1
-1
-1
1
1
1
1
-1
-1
-1
1
1
1
1
1
-1
1
-1
1
1
1
1
1
-1
-1
-1
1
-1
1
1
1
1
1
1
1
1
1
1
1
1
-1
-1
1
1
-1
-1
-1
1
1
1
1
1
-1
1
1
-1
1
1
1
1
1
1
1
-1
1
1
1
1
-1
1
1
1
1
1
1
1
-1
1
1
1
-1
1
-1
1
-1
-1
-1
1
1
1
-1
-1
-1
-1
-1
1
-1
-1
1
1
1
-1
1
-1
1
1
1
-1
-1
-1
1
-1
1
-1
-1
1
-1
1
-1
-1
-1
1
-1
1
-1
1
-1
-1
-1
-1
-1
1
-1
1
1
1
-1
1
1
1
1
-1
1
1
-1
-1
1
1
1
1
1
-1
1
1
1
-1
1
-1
-1
-1
1
-1
-1
-1
-1
1
1
-1
-1
1
1
-1
-1
1
1
-1
-1
1
-1
-1
1
1
-1
1
-1
1
-1
-1
-1
1
1
-1
-1
1
-1
1
-1
1
1
-1
1
1
-1
-1
1
1
-1
1
-1
-1
1
1
-1
1
-1
-1
1
1
1
-1
1
-1
1
-1
1
1
1
1
-1
1
1
1
-1
-1
1
-1
-1
-1
1
-1
-1
-1
1
-1
1
1
1
-1
-1
1
-1
-1
-1
1
-1
1
1
-1
-1
1
1
-1
-1
-1
1
-1
1
1
-1
-1
-1
1
1
1
-1
1
-1
-1
1
-1
1
-1
-1
1
-1
1
1
1
1
1
1
-1
1
1
1
1
-1
1
1
-1
1
-1
-1
1
-1
1
-1
-1
-1
1
1
1
1
1
-1
1
-1
1
1
1
1
1
-1
1
-1
1
-1
-1
1
1
1
-1
-1
1
1
-1
-1
-1
1
1
1
1
1
1
1
-1
-1
-1
1
1
1
1
-1
1
1
-1
-1
1
1
-1
1
1
-1
1
-1
1
-1
1
-1
-1
-1
-1
-1
1
-1
1
1
-1
-1
1
-1
-1
1
-1
-1
1
-1
1
-1
-1
1
-1
1
1
-1
-1
-1
1
-1
-1
-1
-1
-1
1
1
1
-1
1
-1
1
-1
-1
1
1
1
-1
1
1
1
-1
1
-1
1
1
1
-1
1
1
-1
-1
1
1
1
1
1
-1
-1
1
1
1
-1
-1
-1
1
-1
-1
-1
1
1
1
-1
-1
1
-1
1
1
1
-1
1
-1
-1
1
-1
1
-1
-1
-1
1
-1
1
1
1
1
-1
-1
-1
-1
-1
1
-1
-1
1
-1
1
-1
1
1
-1
1
1
-1
-1
-1
1
1
1
-1
-1
1
-1
-1
1
-1
1
-1
-1
-1
1
1
-1
1
-1
1
1
-1
1
-1
-1
-1
1
-1
1
-1
-1
-1
1
1
1
-1
1
-1
-1
1
-1
1
1
1
-1
1
1
1
1
-1
1
1
-1
-1
1
1
1
-1
-1
-1
-1
-1
-1
-1
1
1
-1
-1
-1
-1
-1
1
-1
-1
1
-1
1
-1
-1
-1
1
1
-1
1
1
-1
-1
1
1
1
-1
-1
-1
1
1
1
-1
-1
1
-1
-1
-1
1
1
1
1
1
-1
1
1
1
-1
-1
-1
1
1
-1
-1
-1
-1
-1
1
-1
-1
-1
1
1
1
1
1
1
1
1
-1
-1
-1
1
-1
1
1
1
1
-1
-1
1
-1
1
1
1
-1
-1
1
1
-1
1
1
-1
1
-1
-1
1
-1
1
1
1
1
1
-1
-1
1
1
-1
-1
1
-1
-1
1
1
-1
-1
-1
1
1
1
-1
1
-1
-1
-1
-1
1
-1
1
1
1
-1
1
1
-1
1
-1
-1
1
-1
-1
-1
-1
1
1
-1
-1
1
-1
1
-1
-1
-1
1
-1
-1
-1
1
1
1
1
1
1
1
1
-1
1
1
1
1
1
1
1
-1
-1
-1
-1
1
1
1
1
-1
-1
-1
1
1
-1
-1
1
-1
1
1
-1
-1
-1
1
1
-1
-1
-1
-1
1
-1
1
1
-1
-1
1
-1
1
1
-1
1
-1
-1
1
1
-1
1
-1
1
1
1
1
-1
-1
1
1
-1
-1
1
1
-1
1
-1
-1
-1
-1
1
-1
-1
1
-1
1
-1
-1
-1
1
-1
1
-1
-1
1
-1
1
-1
-1
1
1
1
1
1
1
-1
1
1
1
1
-1
-1
1
-1
1
-1
1
-1
1
-1
-1
-1
-1
-1
-1
-1
-1
-1
1
1
1
1
1
1
1
-1
1
-1
-1
1
1
1
1
-1
1
-1
1
1
1
-1
1
-1
1
1
1
-1
1
-1
-1
1
1
1
1
1
-1
1
-1
1
-1
-1
1
1
-1
1
-1
-1
1
1
-1
-1
1
-1
1
1
1
-1
-1
1
1
1
-1
1
1
1
1
1
-1
1
1
-1
1
-1
1
1
-1
-1
-1
-1
1
1
-1
-1
1
1
1
1
1
1
1
1
-1
1
-1
-1
1
-1
-1
-1
-1
-1
-1
-1
-1
1
1
-1
1
-1
-1
1
1
1
1
1
1
-1
1
-1
1
1
1
-1
1
1
1
1
1
1
1
-1
1
1
-1
1
1
-1
-1
-1
1
1
-1
1
1
1
-1
1
1
1
-1
1
-1
1
-1
1
-1
1
1
1
1
1
1
1
-1
-1
1
1
-1
-1
1
1
-1
1
1
1
1
1
1
-1
-1
-1
1
1
1
1
1
-1
-1
1
-1
-1
1
1
1
1
1
1
1
-1
1
1
1
-1
1
-1
1
1
-1
1
1
1
1
-1
-1
1
-1
1
1
1
1
-1
-1
1
1
-1
1
-1
1
1
-1
1
1
1
1
-1
-1
-1
1
-1
1
1
-1
-1
1
1
-1
1
1
1
1
1
1
1
-1
1
1
1
1
1
1
1
1
1
1
1
1
-1
-1
-1
-1
-1
-1
-1
-1
1
1
1
-1
-1
1
1
1
1
1
1
1
-1
1
-1
1
1
1
1
-1
-1
1
-1
1
-1
1
-1
-1
1
-1
-1
-1
-1
1
1
1
-1
-1
-1
-1
1
1
1
1
-1
-1
1
1
-1
-1
1
1
-1
-1
-1
-1
-1
-1
1
-1
-1
-1
1
-1
1
-1
1
1
1
1
-1
-1
1
-1
1
1
-1
1
1
1
1
-1
1
1
1
1
1
1
1
1
-1
1
-1
-1
1
1
1
-1
-1
1
-1
1
1
1
-1
1
1
1
-1
-1
-1
-1
-1
1
1
1
1
-1
-1
-1
1
1
1
1
1
-1
1
-1
1
1
1
1
1
-1
-1
-1
1
-1
1
1
1
1
1
1
1
1
1
1
1
1
-1
-1
1
1
-1
-1
-1
1
1
1
1
1
-1
1
1
-1
1
1
1
1
1
1
1
-1
1
1
1
1
-1
1
1
1
1
1
1
1
-1
1
1
1
-1
1
-1
1
-1
-1
-1
1
1
1
-1
-1
-1
-1
-1
1
-1
-1
1
1
1
-1
1
-1
1
1
1
-1
-1
-1
1
-1
1
-1
-1
1
-1
1
-1
-1
-1
1
-1
1
-1
1
-1
-1
-1
-1
-1
1
-1
1
1
1
-1
1
1
1
1
-1
1
1
-1
-1
1
1
1
1
1
-1
1
1
1
-1
1
-1
-1
-1
1
-1
-1
-1
-1
1
1
-1
-1
1
1
-1
-1
1
1
-1
-1
1
-1
-1
1
1
-1
1
-1
1
-1
-1
-1
1
1
-1
-1
1
-1
1
-1
1
1
-1
1
1
-1
-1
1
1
-1
1
-1
-1
1
1
-1
1
-1
-1
1
1
1
-1
1
-1
1
-1
1
1
1
1
-1
1
1
1
-1
-1
1
-1
-1
-1
1
-1
-1
-1
1
-1
1
1
1
-1
-1
1
-1
-1
-1
1
-1
1
1
-1
-1
1
1
-1
-1
-1
1
-1
1
1
-1
-1
-1
1
1
1
-1
1
-1
-1
1
-1
1
-1
-1
1
-1
1
1
1
1
1
1
-1
1
1
1
1
-1
1
1
-1
1
-1
-1
1
-1
1
-1
-1
-1
1
1
1
1
1
-1
1
-1
1
1
1
1
1
-1
1
-1
1
-1
-1
1
1
1
-1
-1
1
1
-1
-1
-1
1
1
1
1
1
1
1
-1
-1
-1
1
1
1
1
-1
1
1
-1
-1
1
1
-1
1
1
-1
1
-1
1
-1
1
-1
-1
-1
-1
-1
1
-1
1
1
-1
-1
1
-1
-1
1
-1
-1
1
-1
1
-1
-1
1
-1
1
1
-1
-1
-1
1
-1
-1
-1
-1
-1
1
1
1
-1
1
-1
1
-1
-1
1
1
1
-1
1
1
1
-1
1
-1
1
1
1
-1
1
1
-1
-1
1
1
1
1
1
-1
-1
1
1
1
-1
-1
-1
1
-1
-1
-1
1
1
1
-1
-1
1
-1
1
1
1
-1
1
-1
-1
1
-1
1
-1
-1
-1
1
-1
1
1
1
1
-1
-1
-1
-1
-1
1
-1
-1
1
-1
1
-1
1
1
-1
1
1
-1
-1
-1
1
1
1
-1
-1
1
-1
-1
1
-1
1
-1
-1
-1
1
1
-1
1
-1
1
1
-1
1
-1
-1
-1
1
-1
1
-1
-1
-1
1
1
1
-1
1
-1
-1
1
-1
1
1
1
-1
1
1
1
1
-1
1
1
-1
-1
1
1
1
-1
-1
-1
-1
-1
-1
-1
1
1
-1
-1
-1
-1
-1
1
-1
-1
1
-1
1
-1
-1
-1
1
1
-1
1
1
-1
-1
1
1
1
-1
-1
-1
1
1
1
-1
-1
1
-1
-1
-1
1
1
1
1
1
-1
1
1
1
-1
-1
-1
1
1
-1
-1
-1
-1
-1
1
-1
-1
-1
1
1
1
1
1
1
1
1
-1
-1
-1
1
-1
1
1
1
1
-1
-1
1
-1
1
1
1
-1
-1
1
1
-1
1
1
-1
1
-1
-1
1
-1
1
1
1
1
1
-1
-1
1
1
-1
-1
1
-1
-1
1
1
-1
-1
-1
1
1
1
-1
1
-1
-1
-1
-1
1
-1
1
1
1
-1
1
1
-1
1
-1
-1
1
-1
1
1
-1
1
-1
-1
-1
-1
1
1
1
1
-1
1
-1
1
1
1
-1
1
-1
-1
-1
1
-1
-1
1
1
-1
-1
1
1
1
1
-1
1
1
1
-1
-1
1
1
-1
-1
1
1
1
1
1
1
1
1
1
1
1
-1
1
1
1
1
-1
1
1
1
-1
1
1
1
-1
-1
-1
1
-1
1
1
1
1
-1
1
-1
1
-1
1
1
1
1
-1
1
1
-1
1
1
1
-1
-1
1
-1
1
1
1
1
1
1
1
-1
-1
1
1
-1
1
-1
1
-1
1
1
-1
-1
1
1
-1
-1
-1
1
-1
1
1
1
-1
1
1
-1
-1
1
-1
1
-1
-1
-1
1
-1
1
1
1
1
-1
1
1
1
1
-1
1
-1
1
1
-1
1
-1
-1
-1
-1
-1
-1
1
-1
-1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
-1
1
1
-1
1
1
-1
-1
-1
-1
-1
-1
-1
1
1
-1
-1
-1
1
1
-1
1
-1
1
-1
-1
1
1
1
1
-1
-1
-1
-1
-1
1
1
1
1
1
-1
1
1
1
1
1
1
1
-1
-1
1
1
-1
1
1
-1
-1
1
1
1
-1
1
1
1
1
-1
1
-1
1
1
-1
1
1
-1
-1
-1
-1
1
-1
1
1
1
-1
1
1
1
-1
1
1
1
-1
1
-1
1
-1
1
1
-1
-1
1
1
-1
1
1
1
1
-1
-1
1
1
-1
-1
1
-1
1
1
1
1
1
1
1
1
1
-1
-1
-1
1
-1
-1
1
-1
-1
-1
1
1
1
-1
1
1
-1
-1
1
-1
1
1
-1
1
-1
-1
1
-1
1
1
1
1
1
1
1
-1
-1
1
-1
-1
-1
-1
-1
-1
-1
1
1
1
1
1
1
1
1
1
1
-1
-1
-1
1
1
1
1
1
1
-1
1
-1
-1
1
-1
1
1
-1
-1
-1
1
1
1
1
1
1
1
1
-1
-1
1
-1
1
1
-1
1
1
1
1
1
1
-1
1
1
-1
1
-1
1
-1
-1
-1
1
-1
1
1
1
1
1
1
-1
-1
1
1
1
1
-1
-1
1
-1
-1
-1
1
-1
1
-1
-1
-1
1
1
1
-1
-1
-1
-1
-1
1
-1
1
1
1
1
1
-1
1
1
-1
-1
1
-1
1
1
1
1
1
1
-1
1
1
1
1
-1
1
1
-1
1
1
-1
-1
-1
-1
1
-1
1
1
-1
-1
1
-1
1
-1
-1
1
-1
1
1
1
-1
1
-1
1
-1
1
1
1
1
-1
1
-1
1
1
-1
1
-1
-1
1
-1
1
-1
1
-1
-1
1
1
1
1
1
1
-1
-1
1
-1
1
1
-1
-1
-1
1
1
1
-1
1
1
-1
-1
1
1
1
-1
1
-1
-1
-1
1
1
-1
1
1
1
-1
-1
-1
1
1
-1
1
1
-1
-1
-1
1
1
1
-1
-1
-1
-1
1
-1
1
1
1
1
-1
-1
-1
1
-1
1
-1
1
-1
1
-1
1
1
-1
1
1
-1
-1
1
-1
-1
-1
1
1
-1
-1
-1
-1
-1
-1
-1
-1
1
-1
1
-1
-1
-1
-1
-1
1
-1
1
-1
1
-1
-1
-1
-1
1
-1
1
1
-1
1
1
1
1
-1
-1
-1
-1
1
1
1
-1
-1
1
-1
1
1
1
-1
1
-1
1
-1
1
-1
-1
-1
-1
-1
-1
-1
-1
-1
1
1
1
-1
1
-1
1
-1
1
-1
1
-1
-1
1
-1
-1
1
1
1
1
1
-1
-1
-1
-1
-1
1
-1
-1
-1
-1
1
1
-1
1
-1
1
1
-1
1
1
-1
1
-1
1
1
1
1
-1
1
1
-1
-1
-1
-1
1
-1
-1
1
-1
-1
-1
1
1
1
1
-1
-1
-1
1
-1
-1
1
-1
1
-1
1
1
1
1
-1
1
1
-1
-1
1
-1
-1
1
1
-1
1
-1
1
1
-1
-1
-1
-1
-1
1
-1
-1
-1
1
-1
1
1
1
1
-1
1
-1
-1
-1
-1
-1
1
-1
1
1
-1
1
1
1
1
1
1
1
-1
1
1
1
1
1
1
1
1
-1
-1
1
-1
-1
-1
1
1
1
1
1
-1
-1
-1
-1
1
-1
-1
-1
1
1
-1
1
-1
-1
-1
1
1
1
1
-1
1
1
1
-1
-1
1
-1
1
-1
1
-1
-1
1
-1
-1
1
1
-1
-1
1
-1
-1
1
1
1
-1
1
1
-1
1
1
1
1
-1
-1
1
-1
1
-1
1
1
-1
1
-1
-1
1
1
1
-1
1
-1
-1
1
-1
1
1
1
-1
1
-1
1
1
1
-1
1
-1
1
1
-1
-1
1
1
-1
1
1
1
-1
1
-1
-1
-1
1
1
1
1
-1
1
-1
1
1
-1
-1
-1
1
-1
1
1
1
-1
1
-1
1
1
1
1
1
-1
-1
1
1
-1
1
1
1
1
1
1
-1
-1
1
-1
-1
1
1
1
-1
1
1
-1
-1
1
-1
-1
-1
1
-1
-1
-1
-1
1
1
1
-1
1
-1
-1
1
1
-1
-1
-1
-1
1
-1
1
1
1
1
1
1
-1
1
-1
1
1
-1
-1
1
-1
-1
1
1
-1
-1
1
1
-1
1
1
1
1
-1
-1
-1
1
1
-1
-1
-1
1
-1
-1
1
1
-1
-1
1
-1
-1
1
-1
-1
-1
1
1
1
-1
1
1
-1
-1
-1
1
1
1
1
-1
-1
1
-1
-1
-1
1
-1
-1
1
1
-1
1
-1
1
1
1
-1
1
1
-1
1
-1
-1
1
1
-1
1
-1
1
-1
-1
1
1
-1
1
1
1
-1
-1
1
-1
-1
-1
1
1
1
1
1
1
1
-1
-1
-1
1
1
1
1
1
-1
1
-1
1
-1
1
-1
-1
1
1
1
-1
-1
-1
1
-1
-1
-1
1
-1
1
-1
1
1
-1
-1
1
-1
1
-1
1
1
1
1
-1
1
1
-1
1
1
1
1
-1
-1
1
-1
1
1
-1
1
1
1
-1
-1
1
-1
-1
1
1
1
1
-1
-1
-1
-1
1
-1
1
1
1
1
1
-1
1
1
-1
1
-1
-1
1
-1
1
-1
1
-1
1
-1
-1
1
1
1
1
1
-1
-1
1
1
1
-1
-1
-1
1
1
1
1
-1
1
-1
-1
-1
1
1
1
-1
-1
1
-1
-1
1
1
1
1
-1
-1
1
1
-1
-1
-1
-1
-1
1
-1
-1
1
-1
1
-1
1
-1
-1
-1
-1
-1
1
-1
-1
1
1
1
-1
1
1
1
-1
1
1
1
1
-1
1
1
1
1
-1
1
-1
-1
1
1
1
-1
-1
1
-1
1
-1
1
1
1
-1
1
1
1
-1
-1
1
1
1
1
1
1
1
1
1
1
1
1
1
-1
1
-1
1
-1
1
-1
1
-1
1
-1
-1
-1
-1
1
1
-1
-1
-1
-1
1
1
-1
-1
-1
-1
-1
-1
1
1
1
-1
1
-1
1
-1
-1
1
1
1
-1
1
-1
1
-1
1
-1
-1
-1
1
1
1
1
-1
1
-1
1
1
-1
-1
1
1
1
1
-1
-1
1
-1
-1
-1
-1
-1
-1
1
1
1
1
1
1
-1
-1
1
-1
1
-1
1
1
-1
-1
-1
-1
1
1
-1
1
1
1
1
-1
1
-1
1
-1
-1
-1
-1
1
1
-1
1
-1
1
-1
1
-1
1
1
1
1
1
1
1
-1
-1
1
1
1
1
1
1
-1
1
-1
1
1
1
1
1
-1
-1
-1
1
-1
1
1
-1
1
-1
1
1
-1
1
-1
1
1
1
-1
1
1
1
-1
-1
1
1
-1
-1
-1
1
1
-1
-1
1
-1
1
-1
-1
-1
1
1
1
1
1
-1
1
-1
1
-1
-1
1
1
1
1
1
-1
-1
-1
-1
1
-1
1
1
1
-1
1
-1
-1
1
-1
-1
-1
-1
-1
-1
-1
1
1
1
1
1
-1
1
-1
1
1
-1
1
1
1
1
-1
1
-1
1
-1
1
1
1
-1
1
-1
-1
-1
-1
-1
-1
-1
-1
1
-1
-1
1
1
1
-1
1
1
-1
-1
1
1
-1
-1
1
-1
1
-1
-1
-1
1
1
1
-1
1
-1
-1
1
1
-1
-1
1
-1
1
1
1
1
1
1
-1
1
1
1
-1
1
1
-1
-1
1
1
1
1
1
1
-1
1
-1
-1
1
1
-1
-1
-1
1
-1
-1
1
1
-1
-1
1
-1
1
-1
1
-1
1
-1
-1
-1
-1
1
1
1
-1
1
1
-1
1
-1
-1
1
1
1
1
1
1
-1
1
-1
1
1
1
1
1
1
-1
-1
1
-1
-1
-1
-1
1
-1
1
1
1
1
1
-1
-1
1
1
1
1
1
1
1
-1
-1
-1
-1
1
-1
-1
-1
1
-1
-1
1
1
1
1
1
1
-1
-1
1
-1
1
-1
-1
1
1
-1
1
1
1
-1
-1
1
-1
1
-1
1
-1
1
1
1
-1
-1
-1
1
1
-1
1
-1
-1
1
1
-1
1
1
-1
1
1
-1
-1
-1
-1
-1
1
-1
-1
1
1
1
-1
1
-1
-1
-1
-1
-1
1
-1
-1
1
1
1
1
1
-1
1
-1
1
-1
1
-1
-1
-1
1
1
1
1
1
-1
1
1
1
1
1
-1
1
1
-1
1
1
-1
1
1
1
-1
1
1
-1
-1
1
-1
1
-1
-1
-1
-1
-1
1
-1
-1
1
-1
1
1
1
-1
-1
1
-1
-1
-1
1
1
-1
1
1
-1
1
1
1
1
-1
1
-1
1
1
1
1
-1
-1
-1
-1
1
-1
-1
1
1
1
-1
1
1
1
1
-1
1
1
1
1
-1
1
1
-1
-1
-1
1
-1
1
1
1
1
1
-1
1
1
1
-1
-1
-1
1
-1
-1
1
-1
1
1
-1
-1
-1
1
-1
-1
-1
1
-1
1
-1
1
-1
-1
1
1
1
-1
1
-1
-1
-1
1
1
1
1
-1
1
-1
1
1
1
-1
1
-1
-1
1
1
-1
-1
-1
-1
1
1
1
-1
-1
1
1
1
1
1
1
1
1
-1
1
1
1
-1
1
1
-1
-1
1
-1
-1
1
-1
1
-1
1
1
1
-1
1
1
-1
-1
-1
1
1
1
1
-1
1
1
1
1
1
1
1
1
-1
1
1
1
1
1
-1
1
1
1
-1
1
1
-1
1
1
1
1
1
-1
-1
-1
1
1
-1
1
1
1
1
1
-1
1
1
1
-1
-1
1
-1
1
1
1
-1
1
-1
1
-1
1
-1
-1
1
-1
-1
-1
1
1
1
1
1
1
-1
-1
1
1
1
1
-1
-1
1
-1
1
-1
1
1
-1
1
1
1
1
-1
1
-1
1
-1
1
-1
1
1
1
1
-1
-1
1
-1
-1
1
1
1
-1
1
-1
1
1
1
1
-1
-1
-1
1
1
-1
-1
-1
-1
-1
-1
1
-1
1
-1
-1
1
1
1
-1
1
-1
-1
1
-1
-1
-1
-1
1
1
1
-1
1
1
-1
-1
-1
1
-1
-1
1
1
-1
-1
-1
1
-1
1
1
1
1
-1
-1
-1
-1
1
1
-1
-1
-1
1
-1
-1
-1
1
-1
1
1
-1
1
1
1
-1
1
-1
1
1
1
1
-1
-1
1
1
1
1
-1
1
1
1
1
-1
-1
1
-1
1
1
1
-1
-1
1
1
1
-1
1
1
1
1
1
-1
-1
1
-1
1
-1
1
1
1
-1
-1
-1
-1
1
1
-1
1
1
1
-1
1
1
-1
1
-1
1
1
1
-1
-1
1
-1
1
-1
-1
-1
-1
-1
-1
-1
1
-1
1
1
1
1
-1
-1
-1
-1
-1
1
1
1
-1
1
1
-1
1
-1
-1
-1
1
1
-1
-1
1
1
-1
1
-1
1
1
1
1
-1
1
-1
1
1
-1
-1
-1
-1
1
-1
1
1
1
1
-1
-1
1
1
-1
1
-1
-1
-1
-1
1
-1
1
-1
-1
1
-1
-1
1
-1
-1
-1
-1
1
-1
1
1
1
-1
-1
1
-1
-1
1
-1
1
-1
-1
1
-1
-1
-1
-1
-1
1
-1
1
1
1
-1
1
1
1
-1
-1
1
1
1
-1
1
1
-1
-1
1
1
1
-1
1
1
1
-1
1
1
1
-1
1
1
-1
1
1
1
-1
1
1
-1
-1
-1
-1
1
-1
-1
-1
1
-1
-1
-1
-1
1
1
1
1
1
-1
-1
1
1
-1
1
1
1
1
-1
-1
-1
1
1
1
1
-1
1
-1
-1
-1
-1
-1
1
1
1
-1
1
-1
-1
1
1
1
1
-1
1
1
1
-1
1
1
1
1
1
1
1
-1
-1
-1
1
-1
1
1
-1
1
-1
-1
1
-1
-1
1
-1
1
1
-1
-1
1
1
-1
1
-1
-1
-1
-1
1
1
1
1
-1
1
-1
1
1
1
-1
1
-1
-1
-1
1
-1
-1
1
1
-1
-1
1
1
1
1
-1
1
1
1
-1
-1
1
1
-1
-1
1
1
1
1
1
1
1
1
1
1
1
-1
1
1
1
1
-1
-1
1
-1
-1
-1
-1
-1
-1
-1
1
1
1
1
1
1
1
1
1
1
-1
-1
-1
1
1
1
1
1
1
-1
1
-1
-1
1
-1
1
1
-1
-1
-1
1
1
1
1
1
1
1
1
-1
-1
1
-1
1
1
-1
1
1
1
1
1
1
-1
1
1
-1
1
-1
1
-1
-1
-1
1
-1
1
1
1
1
1
1
-1
-1
1
-1
1
-1
-1
1
-1
-1
-1
1
1
1
1
-1
-1
-1
1
-1
-1
1
-1
1
-1
1
1
1
1
-1
1
1
-1
-1
1
-1
-1
1
1
-1
1
-1
1
1
-1
-1
-1
-1
-1
1
-1
-1
-1
1
-1
1
1
1
1
-1
1
-1
-1
-1
-1
-1
1
-1
1
1
-1
1
1
1
-1
1
1
-1
1
-1
-1
-1
-1
1
1
1
1
-1
1
-1
1
1
1
-1
1
-1
-1
-1
1
-1
-1
1
1
-1
-1
1
1
1
1
-1
1
1
1
-1
-1
1
1
-1
-1
1
1
1
1
1
1
1
1
1
1
1
-1
1
1
1
1
-1
1
1
1
-1
1
1
1
-1
-1
-1
1
-1
1
1
1
1
-1
1
-1
1
-1
1
1
1
1
-1
1
1
-1
1
1
1
-1
-1
1
-1
1
1
1
1
1
1
1
-1
-1
1
1
-1
1
-1
1
-1
1
1
-1
-1
1
1
-1
-1
-1
1
-1
1
1
1
-1
1
1
-1
-1
1
-1
1
-1
-1
-1
1
-1
1
1
1
1
-1
1
1
1
1
-1
1
-1
1
1
-1
1
-1
-1
-1
-1
-1
-1
1
-1
-1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
-1
1
1
-1
1
1
-1
-1
-1
-1
-1
-1
-1
1
1
-1
-1
-1
1
1
-1
1
-1
1
-1
-1
1
1
1
1
-1
-1
-1
-1
-1
1
1
1
1
1
-1
1
1
1
1
1
1
1
-1
-1
1
1
-1
1
1
-1
-1
1
1
1
-1
1
1
1
1
-1
1
-1
1
1
-1
1
1
-1
-1
-1
-1
1
-1
1
1
1
-1
1
1
1
-1
1
1
1
-1
1
-1
1
-1
1
1
-1
-1
1
1
-1
1
1
1
1
-1
-1
1
1
-1
-1
1
-1
1
1
1
1
1
1
1
1
1
-1
-1
-1
1
-1
-1
1
-1
-1
-1
1
1
1
-1
1
1
-1
-1
1
-1
1
1
-1
1
-1
-1
1
-1
1
1
1
1
1
1
1
-1
-1
1
-1
-1
-1
-1
-1
-1
-1
1
1
1
1
1
1
1
1
1
1
-1
-1
-1
1
1
1
1
1
1
-1
1
-1
-1
1
-1
1
1
-1
-1
-1
1
1
1
1
1
1
1
1
-1
-1
1
-1
1
1
-1
1
1
1
1
1
1
-1
1
1
-1
1
-1
1
-1
-1
-1
1
-1
1
1
1
1
1
1
-1
-1
1
1
1
1
-1
-1
1
-1
-1
-1
1
-1
1
-1
-1
-1
1
1
1
-1
-1
-1
-1
-1
1
-1
1
1
1
1
1
-1
1
1
-1
-1
1
-1
1
1
1
1
1
1
-1
1
1
1
1
-1
1
1
-1
1
1
-1
-1
-1
-1
1
-1
1
1
-1
-1
1
-1
1
-1
-1
1
-1
1
1
1
-1
1
-1
1
-1
1
1
1
1
-1
1
-1
1
1
-1
1
-1
-1
1
-1
1
-1
1
-1
-1
1
1
1
1
1
1
-1
-1
1
-1
1
1
-1
-1
-1
1
1
1
-1
1
1
-1
-1
1
1
1
-1
1
-1
-1
-1
1
1
-1
1
1
1
-1
-1
-1
1
1
-1
1
1
-1
-1
-1
1
1
1
-1
-1
-1
-1
1
-1
1
1
1
1
-1
-1
-1
1
-1
1
-1
1
-1
1
-1
1
1
-1
1
1
-1
-1
1
-1
-1
-1
1
1
-1
-1
-1
-1
-1
-1
-1
-1
1
-1
1
-1
-1
-1
-1
-1
1
-1
1
-1
1
-1
-1
-1
-1
1
-1
1
1
-1
1
1
1
1
-1
-1
-1
-1
1
1
1
-1
-1
1
-1
1
1
1
-1
1
-1
1
-1
1
-1
-1
-1
-1
-1
-1
-1
-1
-1
1
1
1
-1
1
-1
1
-1
1
-1
1
-1
-1
1
-1
-1
1
1
1
1
1
-1
-1
-1
-1
-1
1
-1
-1
-1
-1
1
1
-1
1
-1
1
1
-1
1
1
-1
1
-1
1
1
1
1
-1
1
1
-1
-1
-1
-1
1
-1
-1
1
-1
-1
-1
1
1
1
1
-1
-1
-1
1
-1
-1
1
-1
1
-1
1
1
1
1
-1
1
1
-1
-1
1
-1
-1
1
1
-1
1
-1
1
1
-1
-1
-1
-1
-1
1
-1
-1
-1
1
-1
1
1
1
1
-1
1
-1
-1
-1
-1
-1
1
-1
1
1
-1
1
1
1
1
1
1
1
-1
1
1
1
1
1
1
1
1
-1
-1
1
-1
-1
-1
1
1
1
1
1
-1
-1
-1
-1
1
-1
-1
-1
1
1
-1
1
-1
-1
-1
1
1
1
1
-1
1
1
1
-1
-1
1
-1
1
-1
1
-1
-1
1
-1
-1
1
1
-1
-1
1
-1
-1
1
1
1
-1
1
1
-1
1
1
1
1
-1
-1
1
-1
1
-1
1
1
-1
1
-1
-1
1
1
1
-1
1
-1
-1
1
-1
1
1
1
-1
1
-1
1
1
1
-1
1
-1
1
1
-1
-1
1
1
-1
1
1
1
-1
1
-1
-1
-1
1
1
1
1
-1
1
-1
1
1
-1
-1
-1
1
-1
1
1
1
-1
1
-1
1
1
1
1
1
-1
-1
1
1
-1
1
1
1
1
1
1
-1
-1
1
-1
-1
1
1
1
-1
1
1
-1
-1
1
-1
-1
-1
1
-1
-1
-1
-1
1
1
1
-1
1
-1
-1
1
1
-1
-1
-1
-1
1
-1
1
1
1
1
1
1
-1
1
-1
1
1
-1
-1
1
-1
-1
1
1
-1
-1
1
1
-1
1
1
1
1
-1
-1
-1
1
1
-1
-1
-1
1
-1
-1
1
1
-1
-1
1
-1
-1
1
-1
-1
-1
1
1
1
-1
1
1
-1
-1
-1
1
1
1
1
-1
-1
1
-1
-1
-1
1
-1
-1
1
1
-1
1
-1
1
1
1
-1
1
1
-1
1
-1
-1
1
1
-1
1
-1
1
-1
-1
1
1
-1
1
1
1
-1
-1
1
-1
-1
-1
1
1
1
1
1
1
1
-1
-1
-1
1
1
1
1
1
-1
1
-1
1
-1
1
-1
-1
1
1
1
-1
-1
-1
1
-1
-1
-1
1
-1
1
-1
1
1
-1
-1
1
-1
1
-1
1
1
1
1
-1
1
1
-1
1
1
1
1
-1
-1
1
-1
1
1
-1
1
1
1
-1
-1
1
-1
-1
1
1
1
1
-1
-1
-1
-1
1
-1
1
1
1
1
1
-1
1
1
-1
1
-1
-1
1
-1
1
-1
1
-1
1
-1
-1
1
1
1
1
1
-1
-1
1
1
1
-1
-1
-1
1
1
1
1
-1
1
-1
-1
-1
1
1
1
-1
-1
1
-1
-1
1
1
1
1
-1
-1
1
1
-1
-1
-1
-1
-1
1
-1
-1
1
-1
1
-1
1
-1
-1
-1
-1
-1
1
-1
-1
1
1
1
-1
1
1
1
-1
1
1
1
1
-1
1
1
1
1
-1
1
-1
-1
1
1
1
-1
-1
1
-1
1
-1
1
1
1
-1
1
1
1
-1
-1
1
1
1
1
1
1
1
1
1
1
1
1
1
-1
1
-1
1
-1
1
-1
1
-1
1
-1
-1
-1
-1
1
1
-1
-1
-1
-1
1
1
-1
-1
-1
-1
-1
-1
1
1
1
-1
1
-1
1
-1
-1
1
1
1
-1
1
-1
1
-1
1
-1
-1
-1
1
1
1
1
-1
1
-1
1
1
-1
-1
1
1
1
1
-1
-1
1
-1
-1
-1
-1
-1
-1
1
1
1
1
1
1
-1
-1
1
-1
1
-1
1
1
-1
-1
-1
-1
1
1
-1
1
1
1
1
-1
1
-1
1
-1
-1
-1
-1
1
1
-1
1
-1
1
-1
1
-1
1
1
1
1
1
1
1
-1
-1
1
1
1
1
1
1
-1
1
-1
1
1
1
1
1
-1
-1
-1
1
-1
1
1
-1
1
-1
1
1
-1
1
-1
1
1
1
-1
1
1
1
-1
-1
1
1
-1
-1
-1
1
1
-1
-1
1
-1
1
-1
-1
-1
1
1
1
1
1
-1
1
-1
1
-1
-1
1
1
1
1
1
-1
-1
-1
-1
1
-1
1
1
1
-1
1
-1
-1
1
-1
-1
-1
-1
-1
-1
-1
1
1
1
1
1
-1
1
-1
1
1
-1
1
1
1
1
-1
1
-1
1
-1
1
1
1
-1
1
-1
-1
-1
-1
-1
-1
-1
-1
1
-1
-1
1
1
1
-1
1
1
-1
-1
1
1
-1
-1
1
-1
1
-1
-1
-1
1
1
1
-1
1
-1
-1
1
1
-1
-1
1
-1
1
1
1
1
1
1
-1
1
1
1
-1
1
1
-1
-1
1
1
1
1
1
1
-1
1
-1
-1
1
1
-1
-1
-1
1
-1
-1
1
1
-1
-1
1
-1
1
-1
1
-1
1
-1
-1
-1
-1
1
1
1
-1
1
1
-1
1
-1
-1
1
1
1
1
1
1
-1
1
-1
1
1
1
1
1
1
-1
-1
1
-1
-1
-1
-1
1
-1
1
1
1
1
1
-1
-1
1
1
1
1
1
1
1
-1
-1
-1
-1
1
-1
-1
-1
1
-1
-1
1
1
1
1
1
1
-1
-1
1
-1
1
-1
-1
1
1
-1
1
1
1
-1
-1
1
-1
1
-1
1
-1
1
1
1
-1
-1
-1
1
1
-1
1
-1
-1
1
1
-1
1
1
-1
1
1
-1
-1
-1
-1
-1
1
-1
-1
1
1
1
-1
1
-1
-1
-1
-1
-1
1
-1
-1
1
1
1
1
1
-1
1
-1
1
-1
1
-1
-1
-1
1
1
1
1
1
-1
1
1
1
1
1
-1
1
1
-1
1
1
-1
1
1
1
-1
1
1
-1
-1
1
-1
1
-1
-1
-1
-1
-1
1
-1
-1
1
-1
1
1
1
-1
-1
1
-1
-1
-1
1
1
-1
1
1
-1
1
1
1
1
-1
1
-1
1
1
1
1
-1
-1
-1
-1
1
-1
-1
1
1
1
-1
1
1
1
1
-1
1
1
1
1
-1
1
1
-1
-1
-1
1
-1
1
1
1
1
1
-1
1
1
1
-1
-1
-1
1
-1
-1
1
-1
1
1
-1
-1
-1
1
-1
-1
-1
1
-1
1
-1
1
-1
-1
1
1
1
-1
1
-1
-1
-1
1
1
1
1
-1
1
-1
1
1
1
-1
1
-1
-1
1
1
-1
-1
-1
-1
1
1
1
-1
-1
1
1
1
1
1
1
1
1
-1
1
1
1
-1
1
1
-1
-1
1
-1
-1
1
-1
1
-1
1
1
1
-1
1
1
-1
-1
-1
1
1
1
1
-1
1
1
1
1
1
1
1
1
-1
1
1
1
1
1
-1
1
1
1
-1
1
1
-1
1
1
1
1
1
-1
-1
-1
1
1
-1
1
1
1
1
1
-1
1
1
1
-1
-1
1
-1
1
1
1
-1
1
-1
1
-1
1
-1
-1
1
-1
-1
-1
1
1
1
1
1
1
-1
-1
1
1
1
1
-1
-1
1
-1
1
-1
1
1
-1
1
1
1
1
-1
1
-1
1
-1
1
-1
1
1
1
1
-1
-1
1
-1
-1
1
1
1
-1
1
-1
1
1
1
1
-1
-1
-1
1
1
-1
-1
-1
-1
-1
-1
1
-1
1
-1
-1
1
1
1
-1
1
-1
-1
1
-1
-1
-1
-1
1
1
1
-1
1
1
-1
-1
-1
1
-1
-1
1
1
-1
-1
-1
1
-1
1
1
1
1
-1
-1
-1
-1
1
1
-1
-1
-1
1
-1
-1
-1
1
-1
1
1
-1
1
1
1
-1
1
-1
1
1
1
1
-1
-1
1
1
1
1
-1
1
1
1
1
-1
-1
1
-1
1
1
1
-1
-1
1
1
1
-1
1
1
1
1
1
-1
-1
1
-1
1
-1
1
1
1
-1
-1
-1
-1
1
1
-1
1
1
1
-1
1
1
-1
1
-1
1
1
1
-1
-1
1
-1
1
-1
-1
-1
-1
-1
-1
-1
1
-1
1
1
1
1
-1
-1
-1
-1
-1
1
1
1
-1
1
1
-1
1
-1
-1
-1
1
1
-1
-1
1
1
-1
1
-1
1
1
1
1
-1
1
-1
1
1
-1
-1
-1
-1
1
-1
1
1
1
1
-1
-1
1
1
-1
1
-1
-1
-1
-1
1
-1
1
-1
-1
1
-1
-1
1
-1
-1
-1
-1
1
-1
1
1
1
-1
-1
1
-1
-1
1
-1
1
-1
-1
1
-1
-1
-1
-1
-1
1
-1
1
1
1
-1
1
1
1
-1
-1
1
1
1
-1
1
1
-1
-1
1
1
1
-1
1
1
1
-1
1
1
1
-1
1
1
-1
1
1
1
-1
1
1
-1
-1
-1
-1
1
-1
-1
-1
1
-1
-1
-1
-1
1
1
1
1
1
-1
-1
1
1
-1
1
1
1
1
-1
-1
-1
1
1
1
1
-1
1
-1
-1
-1
-1
-1
1
1
1
-1
1
-1
-1
1
1
1
1
-1
1
1
1
-1
1
1
1
1
1
1
1
-1
-1
-1
1
-1
1
1
-1
1
-1
-1
1
-1
-1
1
-1
1
1
-1
-1
1
1
-1
1
-1
-1
-1
-1
1
1
1
1
-1
1
-1
1
1
1
-1
1
-1
-1
-1
1
-1
-1
1
1
-1
-1
1
1
1
1
-1
1
1
1
-1
-1
1
1
-1
-1
1
1
1
1
1
1
1
1
1
1
1
-1
1
1
1
1
-1
-1
1
-1
-1
-1
-1
-1
-1
-1
1
1
1
1
1
1
1
1
1
1
-1
-1
-1
1
1
1
1
1
1
-1
1
-1
-1
1
-1
1
1
-1
-1
-1
1
1
1
1
1
1
1
1
-1
-1
1
-1
1
1
-1
1
1
1
1
1
1
-1
1
1
-1
1
-1
1
-1
-1
-1
1
-1
1
1
1
1
1
1
-1
-1
1
-1
1
-1
-1
1
-1
-1
-1
1
1
1
1
-1
-1
-1
1
-1
-1
1
-1
1
-1
1
1
1
1
-1
1
1
-1
-1
1
-1
-1
1
1
-1
1
-1
1
1
-1
-1
-1
-1
-1
1
-1
-1
-1
1
-1
1
1
1
1
-1
1
-1
-1
-1
-1
-1
1
-1
1
1
-1
1
1
1
-1
-1
-1
1
1
1
1
-1
-1
1
-1
-1
-1
1
-1
-1
1
1
-1
1
-1
1
1
1
-1
1
1
-1
1
-1
-1
1
1
-1
1
-1
1
-1
-1
1
1
-1
1
1
1
-1
-1
1
-1
-1
-1
1
1
1
1
1
1
1
-1
-1
-1
1
1
1
1
1
-1
1
-1
1
-1
1
-1
-1
1
1
1
-1
-1
-1
1
-1
-1
-1
1
-1
1
-1
1
1
-1
-1
1
-1
1
-1
1
1
1
1
-1
1
1
-1
1
1
1
1
-1
-1
1
-1
1
1
-1
1
1
1
-1
-1
1
-1
-1
1
1
1
1
-1
-1
-1
-1
1
-1
1
1
1
1
1
-1
1
1
-1
1
-1
-1
1
-1
1
-1
1
-1
1
-1
-1
1
1
1
1
1
-1
-1
1
1
1
-1
-1
-1
1
1
1
1
-1
1
-1
-1
-1
1
1
1
-1
-1
1
-1
-1
1
1
1
1
-1
-1
1
1
-1
-1
-1
-1
-1
1
-1
-1
1
-1
1
-1
1
-1
-1
-1
-1
-1
1
-1
-1
1
1
1
-1
1
1
1
-1
1
1
1
1
-1
1
1
1
1
-1
1
-1
-1
1
1
1
-1
-1
1
-1
1
-1
1
1
1
-1
1
1
1
-1
-1
1
1
1
1
1
1
1
1
1
1
1
1
1
-1
1
-1
1
-1
1
-1
1
-1
1
-1
-1
-1
-1
1
1
-1
-1
-1
-1
1
1
-1
-1
-1
-1
-1
-1
1
1
1
-1
1
-1
1
-1
-1
1
1
1
-1
1
-1
1
-1
1
-1
-1
-1
1
1
1
1
-1
1
-1
1
1
-1
-1
1
1
1
1
-1
-1
1
-1
-1
-1
-1
-1
-1
1
1
1
1
1
1
-1
-1
1
-1
1
-1
1
1
-1
-1
-1
-1
1
1
-1
1
1
1
1
-1
1
-1
1
-1
-1
-1
-1
-1
1
1
-1
1
-1
-1
-1
-1
1
1
1
1