In [1]:
import pandas as pd
f=pd.read_csv("fullGas.csv")
f

,Make,Model,Body,Mileage_km,Price,Year,Country,Condition,Fuel_Type,Fuel_Consumption_l,...,Cylinders,Seats,Doors,Color,Upholstery,Full_Service_History,Non_Smoker_Vehicle,Previous_Owners,Seller,Image_url
0,Abarth,595,Compact,98000,16900,2020.0,IT,Used,Gasoline,6.7,...,4.0,4.0,3.0,White,Full leather,False,False,NaN,Dealer,https://prod.pictures.autoscout24.net/listing-...
1,Abarth,595,Sedan,91500,12500,2017.0,IT,Used,Gasoline,6.0,...,4.0,4.0,3.0,Grey,Full leather,False,True,4.0,Dealer,https://prod.pictures.autoscout24.net/listing-...
2,Abarth,595,Compact,40000,17990,2015.0,IT,Used,Gasoline,6.5,...,4.0,4.0,3.0,Bronze,Full leather,True,True,1.0,Dealer,https://prod.pictures.autoscout24.net/listing-...
3,Abarth,500,Compact,133000,9300,2008.0,IT,Used,Gasoline,6.5,...,4.0,4.0,3.0,Black,Cloth,True,True,2.0,Dealer,https://prod.pictures.autoscout24.net/listing-...
4,Abarth,595,Compact,61019,14990,2021.0,BE,Used,Gasoline,NaN,...,4.0,4.0,3.0,Yellow,Part leather,True,True,1.0,Dealer,https://prod.pictures.autoscout24.net/listing-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40489,Volvo,V60 Cross Country,Station wagon,73627,32990,2023.0,DE,Used,Diesel,NaN,...,NaN,5.0,5.0,Grey,Part leather,True,True,1.0,Dealer,https://prod.pictures.autoscout24.net/listing-...
40490,Volvo,XC60,Off-Road/Pick-up,93671,26990,2020.0,IT,Used,Electric/Diesel,NaN,...,4.0,5.0,5.0,Grey,Cloth,False,False,NaN,Dealer,https://prod.pictures.autoscout24.net/listing-...
40491,Volvo,V90,Station wagon,60200,32490,2020.0,DE,Used,Gasoline,NaN,...,4.0,5.0,5.0,Black,Full leather,True,True,2.0,Dealer,https://prod.pictures.autoscout24.net/listing-...
40492,Volvo,XC40,Off-Road/Pick-up,49088,29450,2022.0,NL,Used,Electric/Gasoline,NaN,...,3.0,5.0,5.0,Black,Cloth,True,False,NaN,Dealer,https://prod.pictures.autoscout24.net/listing-...
40493,Volvo,XC90,Off-Road/Pick-up,124750,43990,2022.0,DE,Used,Diesel,NaN,...,4.0,5.0,5.0,Grey,Full leather,True,True,2.0,Dealer,https://prod.pictures.autoscout24.net/listing-...

In [2]:
f.info

<bound method DataFrame.info of          Make              Model              Body  Mileage_km  Price    Year  \
0      Abarth                595           Compact       98000  16900  2020.0
1      Abarth                595             Sedan       91500  12500  2017.0
2      Abarth                595           Compact       40000  17990  2015.0
3      Abarth                500           Compact      133000   9300  2008.0
4      Abarth                595           Compact       61019  14990  2021.0
...       ...                ...               ...         ...    ...     ...
40489   Volvo  V60 Cross Country     Station wagon       73627  32990  2023.0
40490   Volvo               XC60  Off-Road/Pick-up       93671  26990  2020.0
40491   Volvo                V90     Station wagon       60200  32490  2020.0
40492   Volvo               XC40  Off-Road/Pick-up       49088  29450  2022.0
40493   Volvo               XC90  Off-Road/Pick-up      124750  43990  2022.0

      Country Condition          Fuel_Type  Fuel_Consumption_l  ... Cylinders  \
0          IT      Used           Gasoline                 6.7  ...       4.0
1          IT      Used           Gasoline                 6.0  ...       4.0
2          IT      Used           Gasoline                 6.5  ...       4.0
3          IT      Used           Gasoline                 6.5  ...       4.0
4          BE      Used           Gasoline                 NaN  ...       4.0
...       ...       ...                ...                 ...  ...       ...
40489      DE      Used             Diesel                 NaN  ...       NaN
40490      IT      Used    Electric/Diesel                 NaN  ...       4.0
40491      DE      Used           Gasoline                 NaN  ...       4.0
40492      NL      Used  Electric/Gasoline                 NaN  ...       3.0
40493      DE      Used             Diesel                 NaN  ...       4.0

      Seats  Doors   Color    Upholstery  Full_Service_History  \
0       4.0    3.0   White  Full leather                 False
1       4.0    3.0    Grey  Full leather                 False
2       4.0    3.0  Bronze  Full leather                  True
3       4.0    3.0   Black         Cloth                  True
4       4.0    3.0  Yellow  Part leather                  True
...     ...    ...     ...           ...                   ...
40489   5.0    5.0    Grey  Part leather                  True
40490   5.0    5.0    Grey         Cloth                 False
40491   5.0    5.0   Black  Full leather                  True
40492   5.0    5.0   Black         Cloth                  True
40493   5.0    5.0    Grey  Full leather                  True

       Non_Smoker_Vehicle  Previous_Owners  Seller  \
0                   False              NaN  Dealer
1                    True              4.0  Dealer
2                    True              1.0  Dealer
3                    True              2.0  Dealer
4                    True              1.0  Dealer
...                   ...              ...     ...
40489                True              1.0  Dealer
40490               False              NaN  Dealer
40491                True              2.0  Dealer
40492               False              NaN  Dealer
40493                True              2.0  Dealer

                                               Image_url
0      https://prod.pictures.autoscout24.net/listing-...
1      https://prod.pictures.autoscout24.net/listing-...
2      https://prod.pictures.autoscout24.net/listing-...
3      https://prod.pictures.autoscout24.net/listing-...
4      https://prod.pictures.autoscout24.net/listing-...
...                                                  ...
40489  https://prod.pictures.autoscout24.net/listing-...
40490  https://prod.pictures.autoscout24.net/listing-...
40491  https://prod.pictures.autoscout24.net/listing-...
40492  https://prod.pictures.autoscout24.net/listing-...
40493  https://prod.pictures.autoscout24.net/listing-...

[40494 rows x 25 columns]>

In [3]:
f.describe()

,Mileage_km,Price,Year,Fuel_Consumption_l,Gears,Power_hp,Engine_Size_cc,Cylinders,Seats,Doors,Previous_Owners
count,4.049400e+04,4.049400e+04,38799.000000,12773.000000,25115.000000,40494.000000,34564.000000,30332.000000,38697.000000,39517.000000,22271.000000
mean,7.723058e+04,5.662527e+04,2017.423877,6.727151,5.899024,231.339976,2275.084597,4.713339,4.633667,4.250879,1.406313
std,3.216313e+05,1.820272e+05,9.141150,3.544475,2.012859,179.923677,1540.972728,2.201816,1.652199,1.113654,1.027425
min,0.000000e+00,1.000000e+00,1922.000000,0.100000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000
25%,1.700000e+04,1.368350e+04,2015.000000,4.700000,5.000000,116.000000,1353.000000,4.000000,5.000000,4.000000,1.000000
50%,5.599500e+04,2.219950e+04,2020.000000,5.600000,6.000000,158.000000,1598.000000,4.000000,5.000000,5.000000,1.000000
75%,1.059982e+05,3.600000e+04,2023.000000,7.200000,7.000000,280.000000,2494.000000,4.000000,5.000000,5.000000,2.000000
max,1.677722e+07,9.999999e+06,2026.000000,55.000000,69.000000,3399.000000,67500.000000,50.000000,255.000000,25.000000,94.000000

In [4]:
f.describe()

,Mileage_km,Price,Year,Fuel_Consumption_l,Gears,Power_hp,Engine_Size_cc,Cylinders,Seats,Doors,Previous_Owners
count,4.049400e+04,4.049400e+04,38799.000000,12773.000000,25115.000000,40494.000000,34564.000000,30332.000000,38697.000000,39517.000000,22271.000000
mean,7.723058e+04,5.662527e+04,2017.423877,6.727151,5.899024,231.339976,2275.084597,4.713339,4.633667,4.250879,1.406313
std,3.216313e+05,1.820272e+05,9.141150,3.544475,2.012859,179.923677,1540.972728,2.201816,1.652199,1.113654,1.027425
min,0.000000e+00,1.000000e+00,1922.000000,0.100000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000
25%,1.700000e+04,1.368350e+04,2015.000000,4.700000,5.000000,116.000000,1353.000000,4.000000,5.000000,4.000000,1.000000
50%,5.599500e+04,2.219950e+04,2020.000000,5.600000,6.000000,158.000000,1598.000000,4.000000,5.000000,5.000000,1.000000
75%,1.059982e+05,3.600000e+04,2023.000000,7.200000,7.000000,280.000000,2494.000000,4.000000,5.000000,5.000000,2.000000
max,1.677722e+07,9.999999e+06,2026.000000,55.000000,69.000000,3399.000000,67500.000000,50.000000,255.000000,25.000000,94.000000

In [5]:
f.isnull().sum()

Make                        0
Model                     221
Body                        1
Mileage_km                  0
Price                       0
Year                     1695
Country                  2592
Condition                   0
Fuel_Type                  29
Fuel_Consumption_l      27721
Drivetrain               8634
Gearbox                   480
Gears                   15379
Power_hp                    0
Engine_Size_cc           5930
Cylinders               10162
Seats                    1797
Doors                     977
Color                    2575
Upholstery               7272
Full_Service_History        0
Non_Smoker_Vehicle          0
Previous_Owners         18223
Seller                    150
Image_url                   0
dtype: int64

In [6]:
f.shape

(40494, 25)

In [7]:
f = f.drop(columns=["Fuel_Consumption_l"])
f

,Make,Model,Body,Mileage_km,Price,Year,Country,Condition,Fuel_Type,Drivetrain,...,Cylinders,Seats,Doors,Color,Upholstery,Full_Service_History,Non_Smoker_Vehicle,Previous_Owners,Seller,Image_url
0,Abarth,595,Compact,98000,16900,2020.0,IT,Used,Gasoline,Front Wheel Drive,...,4.0,4.0,3.0,White,Full leather,False,False,NaN,Dealer,https://prod.pictures.autoscout24.net/listing-...
1,Abarth,595,Sedan,91500,12500,2017.0,IT,Used,Gasoline,Front Wheel Drive,...,4.0,4.0,3.0,Grey,Full leather,False,True,4.0,Dealer,https://prod.pictures.autoscout24.net/listing-...
2,Abarth,595,Compact,40000,17990,2015.0,IT,Used,Gasoline,Front Wheel Drive,...,4.0,4.0,3.0,Bronze,Full leather,True,True,1.0,Dealer,https://prod.pictures.autoscout24.net/listing-...
3,Abarth,500,Compact,133000,9300,2008.0,IT,Used,Gasoline,Front Wheel Drive,...,4.0,4.0,3.0,Black,Cloth,True,True,2.0,Dealer,https://prod.pictures.autoscout24.net/listing-...
4,Abarth,595,Compact,61019,14990,2021.0,BE,Used,Gasoline,Front Wheel Drive,...,4.0,4.0,3.0,Yellow,Part leather,True,True,1.0,Dealer,https://prod.pictures.autoscout24.net/listing-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40489,Volvo,V60 Cross Country,Station wagon,73627,32990,2023.0,DE,Used,Diesel,4WD,...,NaN,5.0,5.0,Grey,Part leather,True,True,1.0,Dealer,https://prod.pictures.autoscout24.net/listing-...
40490,Volvo,XC60,Off-Road/Pick-up,93671,26990,2020.0,IT,Used,Electric/Diesel,4WD,...,4.0,5.0,5.0,Grey,Cloth,False,False,NaN,Dealer,https://prod.pictures.autoscout24.net/listing-...
40491,Volvo,V90,Station wagon,60200,32490,2020.0,DE,Used,Gasoline,Front Wheel Drive,...,4.0,5.0,5.0,Black,Full leather,True,True,2.0,Dealer,https://prod.pictures.autoscout24.net/listing-...
40492,Volvo,XC40,Off-Road/Pick-up,49088,29450,2022.0,NL,Used,Electric/Gasoline,Front Wheel Drive,...,3.0,5.0,5.0,Black,Cloth,True,False,NaN,Dealer,https://prod.pictures.autoscout24.net/listing-...
40493,Volvo,XC90,Off-Road/Pick-up,124750,43990,2022.0,DE,Used,Diesel,4WD,...,4.0,5.0,5.0,Grey,Full leather,True,True,2.0,Dealer,https://prod.pictures.autoscout24.net/listing-...

In [8]:
#col = ['Year','Engine_Size_cc','Cylinders','Seats','Doors','Gears','Previous_Owners','Model','country','Drivetrain','Fuel_Type','Gearbox','Color ','Upholstery ','Seller ']

#for column in col:
 #   f[column] = f[column].fillna(f[column].median())

In [9]:
col = ['Year','Engine_Size_cc','Cylinders','Seats','Doors','Gears','Previous_Owners']

for column in col:
    f[column] = f[column].fillna(f[column].median())

In [10]:
f[col].isnull().sum()

Year               0
Engine_Size_cc     0
Cylinders          0
Seats              0
Doors              0
Gears              0
Previous_Owners    0
dtype: int64

In [11]:
f.isnull().sum()

Make                       0
Model                    221
Body                       1
Mileage_km                 0
Price                      0
Year                       0
Country                 2592
Condition                  0
Fuel_Type                 29
Drivetrain              8634
Gearbox                  480
Gears                      0
Power_hp                   0
Engine_Size_cc             0
Cylinders                  0
Seats                      0
Doors                      0
Color                   2575
Upholstery              7272
Full_Service_History       0
Non_Smoker_Vehicle         0
Previous_Owners            0
Seller                   150
Image_url                  0
dtype: int64

In [12]:
f.head()

,Make,Model,Body,Mileage_km,Price,Year,Country,Condition,Fuel_Type,Drivetrain,...,Cylinders,Seats,Doors,Color,Upholstery,Full_Service_History,Non_Smoker_Vehicle,Previous_Owners,Seller,Image_url
0,Abarth,595,Compact,98000,16900,2020.0,IT,Used,Gasoline,Front Wheel Drive,...,4.0,4.0,3.0,White,Full leather,False,False,1.0,Dealer,https://prod.pictures.autoscout24.net/listing-...
1,Abarth,595,Sedan,91500,12500,2017.0,IT,Used,Gasoline,Front Wheel Drive,...,4.0,4.0,3.0,Grey,Full leather,False,True,4.0,Dealer,https://prod.pictures.autoscout24.net/listing-...
2,Abarth,595,Compact,40000,17990,2015.0,IT,Used,Gasoline,Front Wheel Drive,...,4.0,4.0,3.0,Bronze,Full leather,True,True,1.0,Dealer,https://prod.pictures.autoscout24.net/listing-...
3,Abarth,500,Compact,133000,9300,2008.0,IT,Used,Gasoline,Front Wheel Drive,...,4.0,4.0,3.0,Black,Cloth,True,True,2.0,Dealer,https://prod.pictures.autoscout24.net/listing-...
4,Abarth,595,Compact,61019,14990,2021.0,BE,Used,Gasoline,Front Wheel Drive,...,4.0,4.0,3.0,Yellow,Part leather,True,True,1.0,Dealer,https://prod.pictures.autoscout24.net/listing-...

In [13]:
f=f.drop("Image_url",axis=1)
f

,Make,Model,Body,Mileage_km,Price,Year,Country,Condition,Fuel_Type,Drivetrain,...,Engine_Size_cc,Cylinders,Seats,Doors,Color,Upholstery,Full_Service_History,Non_Smoker_Vehicle,Previous_Owners,Seller
0,Abarth,595,Compact,98000,16900,2020.0,IT,Used,Gasoline,Front Wheel Drive,...,1368.0,4.0,4.0,3.0,White,Full leather,False,False,1.0,Dealer
1,Abarth,595,Sedan,91500,12500,2017.0,IT,Used,Gasoline,Front Wheel Drive,...,1368.0,4.0,4.0,3.0,Grey,Full leather,False,True,4.0,Dealer
2,Abarth,595,Compact,40000,17990,2015.0,IT,Used,Gasoline,Front Wheel Drive,...,1368.0,4.0,4.0,3.0,Bronze,Full leather,True,True,1.0,Dealer
3,Abarth,500,Compact,133000,9300,2008.0,IT,Used,Gasoline,Front Wheel Drive,...,1368.0,4.0,4.0,3.0,Black,Cloth,True,True,2.0,Dealer
4,Abarth,595,Compact,61019,14990,2021.0,BE,Used,Gasoline,Front Wheel Drive,...,1368.0,4.0,4.0,3.0,Yellow,Part leather,True,True,1.0,Dealer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40489,Volvo,V60 Cross Country,Station wagon,73627,32990,2023.0,DE,Used,Diesel,4WD,...,1969.0,4.0,5.0,5.0,Grey,Part leather,True,True,1.0,Dealer
40490,Volvo,XC60,Off-Road/Pick-up,93671,26990,2020.0,IT,Used,Electric/Diesel,4WD,...,1969.0,4.0,5.0,5.0,Grey,Cloth,False,False,1.0,Dealer
40491,Volvo,V90,Station wagon,60200,32490,2020.0,DE,Used,Gasoline,Front Wheel Drive,...,1969.0,4.0,5.0,5.0,Black,Full leather,True,True,2.0,Dealer
40492,Volvo,XC40,Off-Road/Pick-up,49088,29450,2022.0,NL,Used,Electric/Gasoline,Front Wheel Drive,...,1477.0,3.0,5.0,5.0,Black,Cloth,True,False,1.0,Dealer
40493,Volvo,XC90,Off-Road/Pick-up,124750,43990,2022.0,DE,Used,Diesel,4WD,...,1969.0,4.0,5.0,5.0,Grey,Full leather,True,True,2.0,Dealer

In [14]:
f.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40494 entries, 0 to 40493
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Make                  40494 non-null  object
 1   Model                 40273 non-null  object
 2   Body                  40493 non-null  object
 3   Mileage_km            40494 non-null  int64
 4   Price                 40494 non-null  int64
 5   Year                  40494 non-null  float64
 6   Country               37902 non-null  object
 7   Condition             40494 non-null  object
 8   Fuel_Type             40465 non-null  object
 9   Drivetrain            31860 non-null  object
 10  Gearbox               40014 non-null  object
 11  Gears                 40494 non-null  float64
 12  Power_hp              40494 non-null  int64
 13  Engine_Size_cc        40494 non-null  float64
 14  Cylinders             40494 non-null  float64
 15  Seats                 40494 non-null  float64
 16  Doors                 40494 non-null  float64
 17  Color                 37919 non-null  object
 18  Upholstery            33222 non-null  object
 19  Full_Service_History  40494 non-null  bool
 20  Non_Smoker_Vehicle    40494 non-null  bool
 21  Previous_Owners       40494 non-null  float64
 22  Seller                40344 non-null  object
dtypes: bool(2), float64(7), int64(3), object(11)
memory usage: 6.6+ MB

In [15]:
fn=f.select_dtypes(include=["int64","float64"]).columns
fn

Index(['Mileage_km', 'Price', 'Year', 'Gears', 'Power_hp', 'Engine_Size_cc',
       'Cylinders', 'Seats', 'Doors', 'Previous_Owners'],
      dtype='object')

In [16]:
f[fn]=f[fn].fillna(f[fn].median())
f[fn].isnull().sum()

Mileage_km         0
Price              0
Year               0
Gears              0
Power_hp           0
Engine_Size_cc     0
Cylinders          0
Seats              0
Doors              0
Previous_Owners    0
dtype: int64

In [17]:
fo=f.select_dtypes(include="object").columns
for i in fo:
    f[i]=f[i].fillna(f[i].mode()[0])
    f[i]

In [18]:
from sklearn.preprocessing import LabelEncoder

In [19]:
d={}
le=LabelEncoder()
for i in fo:
    f[i]=le.fit_transform(f[i])
    d[i]=le

In [20]:
f.isnull().sum()

Make                    0
Model                   0
Body                    0
Mileage_km              0
Price                   0
Year                    0
Country                 0
Condition               0
Fuel_Type               0
Drivetrain              0
Gearbox                 0
Gears                   0
Power_hp                0
Engine_Size_cc          0
Cylinders               0
Seats                   0
Doors                   0
Color                   0
Upholstery              0
Full_Service_History    0
Non_Smoker_Vehicle      0
Previous_Owners         0
Seller                  0
dtype: int64

In [21]:
x=f.drop("Condition",axis=1)
y=f["Condition"]
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40494 entries, 0 to 40493
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Make                  40494 non-null  int64
 1   Model                 40494 non-null  int64
 2   Body                  40494 non-null  int64
 3   Mileage_km            40494 non-null  int64
 4   Price                 40494 non-null  int64
 5   Year                  40494 non-null  float64
 6   Country               40494 non-null  int64
 7   Fuel_Type             40494 non-null  int64
 8   Drivetrain            40494 non-null  int64
 9   Gearbox               40494 non-null  int64
 10  Gears                 40494 non-null  float64
 11  Power_hp              40494 non-null  int64
 12  Engine_Size_cc        40494 non-null  float64
 13  Cylinders             40494 non-null  float64
 14  Seats                 40494 non-null  float64
 15  Doors                 40494 non-null  float64
 16  Color                 40494 non-null  int64
 17  Upholstery            40494 non-null  int64
 18  Full_Service_History  40494 non-null  bool
 19  Non_Smoker_Vehicle    40494 non-null  bool
 20  Previous_Owners       40494 non-null  float64
 21  Seller                40494 non-null  int64
dtypes: bool(2), float64(7), int64(13)
memory usage: 6.3 MB

In [22]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [24]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=100,random_state=42,class_weight="balanced")
model.fit(x_train,y_train)

RandomForestClassifier(class_weight='balanced', random_state=42)

In [25]:
y_pred=model.predict(x_test)

In [30]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))
print("confusion_matric \n",confusion_matrix(y_test, y_pred))
print("classification_repor : \n",classification_report(y_test, y_pred))

Accuracy: 0.9976540313618966
confusion_matric
 [[ 362   18]
 [   1 7718]]
classification_repor :
               precision    recall  f1-score   support

           0       1.00      0.95      0.97       380
           1       1.00      1.00      1.00      7719

    accuracy                           1.00      8099
   macro avg       1.00      0.98      0.99      8099
weighted avg       1.00      1.00      1.00      8099